// Regenerate with: dart run ffigen --config ffigen.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Dynamic-library bindings for the project-owned Fonix C shim.
class FonixDynamicLibraryBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FonixDynamicLibraryBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FonixDynamicLibraryBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int dort_get_abi_version() {
    return _dort_get_abi_version();
  }

  late final _dort_get_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'dort_get_abi_version',
      );
  late final _dort_get_abi_version = _dort_get_abi_versionPtr
      .asFunction<int Function()>();

  int dort_get_ort_api_compatibility_floor() {
    return _dort_get_ort_api_compatibility_floor();
  }

  late final _dort_get_ort_api_compatibility_floorPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'dort_get_ort_api_compatibility_floor',
      );
  late final _dort_get_ort_api_compatibility_floor =
      _dort_get_ort_api_compatibility_floorPtr.asFunction<int Function()>();

  ffi.Pointer<dort_status_t> dort_get_build_manifest_json(
    ffi.Pointer<dort_string_t> out_json,
  ) {
    return _dort_get_build_manifest_json(out_json);
  }

  late final _dort_get_build_manifest_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_string_t>)
        >
      >('dort_get_build_manifest_json');
  late final _dort_get_build_manifest_json = _dort_get_build_manifest_jsonPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_string_t>)
      >();

  void dort_string_release(ffi.Pointer<dort_string_t> string_value) {
    return _dort_string_release(string_value);
  }

  late final _dort_string_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_string_t>)>
      >('dort_string_release');
  late final _dort_string_release = _dort_string_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_string_t>)>();

  int dort_status_domain(ffi.Pointer<dort_status_t> status) {
    return _dort_status_domain(status);
  }

  late final _dort_status_domainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dort_status_t>)>
      >('dort_status_domain');
  late final _dort_status_domain = _dort_status_domainPtr
      .asFunction<int Function(ffi.Pointer<dort_status_t>)>();

  int dort_status_code(ffi.Pointer<dort_status_t> status) {
    return _dort_status_code(status);
  }

  late final _dort_status_codePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dort_status_t>)>
      >('dort_status_code');
  late final _dort_status_code = _dort_status_codePtr
      .asFunction<int Function(ffi.Pointer<dort_status_t>)>();

  int dort_status_ort_code(ffi.Pointer<dort_status_t> status) {
    return _dort_status_ort_code(status);
  }

  late final _dort_status_ort_codePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dort_status_t>)>
      >('dort_status_ort_code');
  late final _dort_status_ort_code = _dort_status_ort_codePtr
      .asFunction<int Function(ffi.Pointer<dort_status_t>)>();

  ffi.Pointer<ffi.Char> dort_status_operation(
    ffi.Pointer<dort_status_t> status,
  ) {
    return _dort_status_operation(status);
  }

  late final _dort_status_operationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)
        >
      >('dort_status_operation');
  late final _dort_status_operation = _dort_status_operationPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)>();

  ffi.Pointer<ffi.Char> dort_status_message(ffi.Pointer<dort_status_t> status) {
    return _dort_status_message(status);
  }

  late final _dort_status_messagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)
        >
      >('dort_status_message');
  late final _dort_status_message = _dort_status_messagePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)>();

  void dort_status_release(ffi.Pointer<dort_status_t> status) {
    return _dort_status_release(status);
  }

  late final _dort_status_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_status_t>)>
      >('dort_status_release');
  late final _dort_status_release = _dort_status_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_status_t>)>();

  ffi.Pointer<dort_status_t> dort_runtime_open(
    ffi.Pointer<dort_runtime_config_t> config,
    ffi.Pointer<ffi.Pointer<dort_runtime_t>> out_runtime,
  ) {
    return _dort_runtime_open(config, out_runtime);
  }

  late final _dort_runtime_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_config_t>,
            ffi.Pointer<ffi.Pointer<dort_runtime_t>>,
          )
        >
      >('dort_runtime_open');
  late final _dort_runtime_open = _dort_runtime_openPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_config_t>,
          ffi.Pointer<ffi.Pointer<dort_runtime_t>>,
        )
      >();

  void dort_runtime_retain(ffi.Pointer<dort_runtime_t> runtime) {
    return _dort_runtime_retain(runtime);
  }

  late final _dort_runtime_retainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_runtime_t>)>
      >('dort_runtime_retain');
  late final _dort_runtime_retain = _dort_runtime_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_runtime_t>)>();

  void dort_runtime_release(ffi.Pointer<dort_runtime_t> runtime) {
    return _dort_runtime_release(runtime);
  }

  late final _dort_runtime_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_runtime_t>)>
      >('dort_runtime_release');
  late final _dort_runtime_release = _dort_runtime_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_runtime_t>)>();

  ffi.Pointer<dort_status_t> dort_runtime_info_json(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_string_t> out_json,
  ) {
    return _dort_runtime_info_json(runtime, out_json);
  }

  late final _dort_runtime_info_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_runtime_info_json');
  late final _dort_runtime_info_json = _dort_runtime_info_jsonPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<dort_string_t>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_runtime_available_providers_json(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_string_t> out_json,
  ) {
    return _dort_runtime_available_providers_json(runtime, out_json);
  }

  late final _dort_runtime_available_providers_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_runtime_available_providers_json');
  late final _dort_runtime_available_providers_json =
      _dort_runtime_available_providers_jsonPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_runtime_t>,
              ffi.Pointer<dort_string_t>,
            )
          >();

  ffi.Pointer<dort_status_t> dort_session_options_create(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_session_config_t> config,
    ffi.Pointer<ffi.Pointer<dort_session_options_t>> out_options,
  ) {
    return _dort_session_options_create(runtime, config, out_options);
  }

  late final _dort_session_options_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_session_config_t>,
            ffi.Pointer<ffi.Pointer<dort_session_options_t>>,
          )
        >
      >('dort_session_options_create');
  late final _dort_session_options_create = _dort_session_options_createPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<dort_session_config_t>,
          ffi.Pointer<ffi.Pointer<dort_session_options_t>>,
        )
      >();

  void dort_session_options_retain(
    ffi.Pointer<dort_session_options_t> options,
  ) {
    return _dort_session_options_retain(options);
  }

  late final _dort_session_options_retainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dort_session_options_t>)
        >
      >('dort_session_options_retain');
  late final _dort_session_options_retain = _dort_session_options_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_session_options_t>)>();

  void dort_session_options_release(
    ffi.Pointer<dort_session_options_t> options,
  ) {
    return _dort_session_options_release(options);
  }

  late final _dort_session_options_releasePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dort_session_options_t>)
        >
      >('dort_session_options_release');
  late final _dort_session_options_release = _dort_session_options_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_session_options_t>)>();

  ffi.Pointer<dort_status_t> dort_session_create_from_bytes(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_session_options_t> options,
    ffi.Pointer<ffi.Void> model_data,
    int model_data_length,
    ffi.Pointer<ffi.Pointer<dort_session_t>> out_session,
  ) {
    return _dort_session_create_from_bytes(
      runtime,
      options,
      model_data,
      model_data_length,
      out_session,
    );
  }

  late final _dort_session_create_from_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_session_options_t>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<dort_session_t>>,
          )
        >
      >('dort_session_create_from_bytes');
  late final _dort_session_create_from_bytes =
      _dort_session_create_from_bytesPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_runtime_t>,
              ffi.Pointer<dort_session_options_t>,
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<ffi.Pointer<dort_session_t>>,
            )
          >();

  ffi.Pointer<dort_status_t> dort_session_create_from_file(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_session_options_t> options,
    ffi.Pointer<ffi.Char> model_path_utf8,
    ffi.Pointer<ffi.Char> allowed_root_utf8,
    ffi.Pointer<ffi.Pointer<dort_session_t>> out_session,
  ) {
    return _dort_session_create_from_file(
      runtime,
      options,
      model_path_utf8,
      allowed_root_utf8,
      out_session,
    );
  }

  late final _dort_session_create_from_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_session_options_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<dort_session_t>>,
          )
        >
      >('dort_session_create_from_file');
  late final _dort_session_create_from_file = _dort_session_create_from_filePtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<dort_session_options_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<dort_session_t>>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_session_create_from_bytes_with_external_data(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_session_options_t> options,
    ffi.Pointer<ffi.Void> model_data,
    int model_data_length,
    ffi.Pointer<dort_external_data_t> external_data,
    int external_data_count,
    ffi.Pointer<ffi.Pointer<dort_session_t>> out_session,
  ) {
    return _dort_session_create_from_bytes_with_external_data(
      runtime,
      options,
      model_data,
      model_data_length,
      external_data,
      external_data_count,
      out_session,
    );
  }

  late final _dort_session_create_from_bytes_with_external_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_session_options_t>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Pointer<dort_external_data_t>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<dort_session_t>>,
          )
        >
      >('dort_session_create_from_bytes_with_external_data');
  late final _dort_session_create_from_bytes_with_external_data =
      _dort_session_create_from_bytes_with_external_dataPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_runtime_t>,
              ffi.Pointer<dort_session_options_t>,
              ffi.Pointer<ffi.Void>,
              int,
              ffi.Pointer<dort_external_data_t>,
              int,
              ffi.Pointer<ffi.Pointer<dort_session_t>>,
            )
          >();

  void dort_session_retain(ffi.Pointer<dort_session_t> session) {
    return _dort_session_retain(session);
  }

  late final _dort_session_retainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_session_t>)>
      >('dort_session_retain');
  late final _dort_session_retain = _dort_session_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_session_t>)>();

  void dort_session_release(ffi.Pointer<dort_session_t> session) {
    return _dort_session_release(session);
  }

  late final _dort_session_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_session_t>)>
      >('dort_session_release');
  late final _dort_session_release = _dort_session_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_session_t>)>();

  ffi.Pointer<dort_status_t> dort_session_metadata_json(
    ffi.Pointer<dort_session_t> session,
    ffi.Pointer<dort_string_t> out_json,
  ) {
    return _dort_session_metadata_json(session, out_json);
  }

  late final _dort_session_metadata_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_session_t>,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_session_metadata_json');
  late final _dort_session_metadata_json = _dort_session_metadata_jsonPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_session_t>,
          ffi.Pointer<dort_string_t>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_session_type_metadata_json(
    ffi.Pointer<dort_session_t> session,
    ffi.Pointer<dort_string_t> out_json,
  ) {
    return _dort_session_type_metadata_json(session, out_json);
  }

  late final _dort_session_type_metadata_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_session_t>,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_session_type_metadata_json');
  late final _dort_session_type_metadata_json =
      _dort_session_type_metadata_jsonPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_session_t>,
              ffi.Pointer<dort_string_t>,
            )
          >();

  ffi.Pointer<dort_status_t> dort_session_model_metadata_json(
    ffi.Pointer<dort_session_t> session,
    ffi.Pointer<dort_string_t> out_json,
  ) {
    return _dort_session_model_metadata_json(session, out_json);
  }

  late final _dort_session_model_metadata_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_session_t>,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_session_model_metadata_json');
  late final _dort_session_model_metadata_json =
      _dort_session_model_metadata_jsonPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_session_t>,
              ffi.Pointer<dort_string_t>,
            )
          >();

  ffi.Pointer<dort_status_t> dort_buffer_allocate(
    ffi.Pointer<dort_runtime_t> runtime,
    int byte_length,
    int alignment,
    ffi.Pointer<ffi.Pointer<dort_buffer_t>> out_buffer,
  ) {
    return _dort_buffer_allocate(runtime, byte_length, alignment, out_buffer);
  }

  late final _dort_buffer_allocatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Size,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<dort_buffer_t>>,
          )
        >
      >('dort_buffer_allocate');
  late final _dort_buffer_allocate = _dort_buffer_allocatePtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<dort_buffer_t>>,
        )
      >();

  void dort_buffer_retain(ffi.Pointer<dort_buffer_t> buffer) {
    return _dort_buffer_retain(buffer);
  }

  late final _dort_buffer_retainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_buffer_t>)>
      >('dort_buffer_retain');
  late final _dort_buffer_retain = _dort_buffer_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_buffer_t>)>();

  void dort_buffer_release(ffi.Pointer<dort_buffer_t> buffer) {
    return _dort_buffer_release(buffer);
  }

  late final _dort_buffer_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_buffer_t>)>
      >('dort_buffer_release');
  late final _dort_buffer_release = _dort_buffer_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_buffer_t>)>();

  int dort_buffer_byte_length(ffi.Pointer<dort_buffer_t> buffer) {
    return _dort_buffer_byte_length(buffer);
  }

  late final _dort_buffer_byte_lengthPtr =
      _lookup<
        ffi.NativeFunction<ffi.Size Function(ffi.Pointer<dort_buffer_t>)>
      >('dort_buffer_byte_length');
  late final _dort_buffer_byte_length = _dort_buffer_byte_lengthPtr
      .asFunction<int Function(ffi.Pointer<dort_buffer_t>)>();

  ffi.Pointer<dort_status_t> dort_buffer_write(
    ffi.Pointer<dort_buffer_t> buffer,
    int offset,
    ffi.Pointer<ffi.Void> source,
    int byte_length,
  ) {
    return _dort_buffer_write(buffer, offset, source, byte_length);
  }

  late final _dort_buffer_writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_buffer_t>,
            ffi.Size,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
          )
        >
      >('dort_buffer_write');
  late final _dort_buffer_write = _dort_buffer_writePtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_buffer_t>,
          int,
          ffi.Pointer<ffi.Void>,
          int,
        )
      >();

  ffi.Pointer<dort_status_t> dort_buffer_read(
    ffi.Pointer<dort_buffer_t> buffer,
    int offset,
    ffi.Pointer<ffi.Void> destination,
    int byte_length,
  ) {
    return _dort_buffer_read(buffer, offset, destination, byte_length);
  }

  late final _dort_buffer_readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_buffer_t>,
            ffi.Size,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
          )
        >
      >('dort_buffer_read');
  late final _dort_buffer_read = _dort_buffer_readPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_buffer_t>,
          int,
          ffi.Pointer<ffi.Void>,
          int,
        )
      >();

  ffi.Pointer<dort_status_t> dort_buffer_data_acquire(
    ffi.Pointer<dort_buffer_t> buffer,
    ffi.Pointer<ffi.Pointer<dort_data_lease_t>> out_lease,
    ffi.Pointer<ffi.Pointer<ffi.Void>> out_data,
    ffi.Pointer<ffi.Size> out_byte_length,
  ) {
    return _dort_buffer_data_acquire(
      buffer,
      out_lease,
      out_data,
      out_byte_length,
    );
  }

  late final _dort_buffer_data_acquirePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_buffer_t>,
            ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('dort_buffer_data_acquire');
  late final _dort_buffer_data_acquire = _dort_buffer_data_acquirePtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_buffer_t>,
          ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_tensor_create_copy(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<ffi.Void> data,
    int byte_length,
    ffi.Pointer<ffi.Int64> dimensions,
    int dimension_count,
    int element_type,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_tensor_create_copy(
      runtime,
      data,
      byte_length,
      dimensions,
      dimension_count,
      element_type,
      out_value,
    );
  }

  late final _dort_tensor_create_copyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Pointer<ffi.Int64>,
            ffi.Size,
            ffi.Uint32,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_tensor_create_copy');
  late final _dort_tensor_create_copy = _dort_tensor_create_copyPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Int64>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_tensor_create_with_buffer(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_buffer_t> buffer,
    int byte_offset,
    int byte_length,
    ffi.Pointer<ffi.Int64> dimensions,
    int dimension_count,
    int element_type,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_tensor_create_with_buffer(
      runtime,
      buffer,
      byte_offset,
      byte_length,
      dimensions,
      dimension_count,
      element_type,
      out_value,
    );
  }

  late final _dort_tensor_create_with_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_buffer_t>,
            ffi.Size,
            ffi.Size,
            ffi.Pointer<ffi.Int64>,
            ffi.Size,
            ffi.Uint32,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_tensor_create_with_buffer');
  late final _dort_tensor_create_with_buffer =
      _dort_tensor_create_with_bufferPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_runtime_t>,
              ffi.Pointer<dort_buffer_t>,
              int,
              int,
              ffi.Pointer<ffi.Int64>,
              int,
              int,
              ffi.Pointer<ffi.Pointer<dort_value_t>>,
            )
          >();

  ffi.Pointer<dort_status_t> dort_tensor_create_strings_copy(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_utf8_span_t> strings,
    int string_count,
    ffi.Pointer<ffi.Int64> dimensions,
    int dimension_count,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_tensor_create_strings_copy(
      runtime,
      strings,
      string_count,
      dimensions,
      dimension_count,
      out_value,
    );
  }

  late final _dort_tensor_create_strings_copyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_utf8_span_t>,
            ffi.Size,
            ffi.Pointer<ffi.Int64>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_tensor_create_strings_copy');
  late final _dort_tensor_create_strings_copy =
      _dort_tensor_create_strings_copyPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_runtime_t>,
              ffi.Pointer<dort_utf8_span_t>,
              int,
              ffi.Pointer<ffi.Int64>,
              int,
              ffi.Pointer<ffi.Pointer<dort_value_t>>,
            )
          >();

  void dort_value_retain(ffi.Pointer<dort_value_t> value) {
    return _dort_value_retain(value);
  }

  late final _dort_value_retainPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_value_t>)>>(
        'dort_value_retain',
      );
  late final _dort_value_retain = _dort_value_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_value_t>)>();

  void dort_value_release(ffi.Pointer<dort_value_t> value) {
    return _dort_value_release(value);
  }

  late final _dort_value_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_value_t>)>>(
        'dort_value_release',
      );
  late final _dort_value_release = _dort_value_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_value_t>)>();

  ffi.Pointer<dort_status_t> dort_value_kind$1(
    ffi.Pointer<dort_value_t> value,
    ffi.Pointer<ffi.Uint32> out_kind,
  ) {
    return _dort_value_kind$1(value, out_kind);
  }

  late final _dort_value_kind$1Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('dort_value_kind');
  late final _dort_value_kind$1 = _dort_value_kind$1Ptr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<ffi.Uint32>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_value_child_count(
    ffi.Pointer<dort_value_t> value,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _dort_value_child_count(value, out_count);
  }

  late final _dort_value_child_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('dort_value_child_count');
  late final _dort_value_child_count = _dort_value_child_countPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_value_child_get(
    ffi.Pointer<dort_value_t> value,
    int index,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_child,
  ) {
    return _dort_value_child_get(value, index, out_child);
  }

  late final _dort_value_child_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_value_child_get');
  late final _dort_value_child_get = _dort_value_child_getPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          int,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_sequence_create(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<ffi.Pointer<dort_value_t>> values,
    int value_count,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_sequence_create(runtime, values, value_count, out_value);
  }

  late final _dort_sequence_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_sequence_create');
  late final _dort_sequence_create = _dort_sequence_createPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
          int,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_map_create(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<dort_value_t> keys,
    ffi.Pointer<dort_value_t> values,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_map_create(runtime, keys, values, out_value);
  }

  late final _dort_map_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_map_create');
  late final _dort_map_create = _dort_map_createPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_optional_none_create(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_optional_none_create(runtime, out_value);
  }

  late final _dort_optional_none_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_optional_none_create');
  late final _dort_optional_none_create = _dort_optional_none_createPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_optional_some_create(
    ffi.Pointer<dort_value_t> contained_value,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_optional_some_create(contained_value, out_value);
  }

  late final _dort_optional_some_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_optional_some_create');
  late final _dort_optional_some_create = _dort_optional_some_createPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_tensor_info_json(
    ffi.Pointer<dort_value_t> value,
    ffi.Pointer<dort_string_t> out_json,
  ) {
    return _dort_tensor_info_json(value, out_json);
  }

  late final _dort_tensor_info_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_tensor_info_json');
  late final _dort_tensor_info_json = _dort_tensor_info_jsonPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<dort_string_t>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_tensor_copy_data(
    ffi.Pointer<dort_value_t> value,
    ffi.Pointer<ffi.Void> destination,
    int destination_capacity,
    ffi.Pointer<ffi.Size> out_required_bytes,
  ) {
    return _dort_tensor_copy_data(
      value,
      destination,
      destination_capacity,
      out_required_bytes,
    );
  }

  late final _dort_tensor_copy_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('dort_tensor_copy_data');
  late final _dort_tensor_copy_data = _dort_tensor_copy_dataPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_tensor_string_count(
    ffi.Pointer<dort_value_t> value,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _dort_tensor_string_count(value, out_count);
  }

  late final _dort_tensor_string_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('dort_tensor_string_count');
  late final _dort_tensor_string_count = _dort_tensor_string_countPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_tensor_string_get(
    ffi.Pointer<dort_value_t> value,
    int index,
    ffi.Pointer<dort_string_t> out_string,
  ) {
    return _dort_tensor_string_get(value, index, out_string);
  }

  late final _dort_tensor_string_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Size,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_tensor_string_get');
  late final _dort_tensor_string_get = _dort_tensor_string_getPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          int,
          ffi.Pointer<dort_string_t>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_tensor_data_acquire(
    ffi.Pointer<dort_value_t> value,
    ffi.Pointer<ffi.Pointer<dort_data_lease_t>> out_lease,
    ffi.Pointer<ffi.Pointer<ffi.Void>> out_data,
    ffi.Pointer<ffi.Size> out_byte_length,
  ) {
    return _dort_tensor_data_acquire(
      value,
      out_lease,
      out_data,
      out_byte_length,
    );
  }

  late final _dort_tensor_data_acquirePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_value_t>,
            ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('dort_tensor_data_acquire');
  late final _dort_tensor_data_acquire = _dort_tensor_data_acquirePtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_value_t>,
          ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void dort_data_lease_retain(ffi.Pointer<dort_data_lease_t> lease) {
    return _dort_data_lease_retain(lease);
  }

  late final _dort_data_lease_retainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_data_lease_t>)>
      >('dort_data_lease_retain');
  late final _dort_data_lease_retain = _dort_data_lease_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_data_lease_t>)>();

  void dort_data_lease_release(ffi.Pointer<dort_data_lease_t> lease) {
    return _dort_data_lease_release(lease);
  }

  late final _dort_data_lease_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_data_lease_t>)>
      >('dort_data_lease_release');
  late final _dort_data_lease_release = _dort_data_lease_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_data_lease_t>)>();

  ffi.Pointer<dort_status_t> dort_run_options_create(
    ffi.Pointer<dort_runtime_t> runtime,
    ffi.Pointer<ffi.Pointer<dort_run_options_t>> out_options,
  ) {
    return _dort_run_options_create(runtime, out_options);
  }

  late final _dort_run_options_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_runtime_t>,
            ffi.Pointer<ffi.Pointer<dort_run_options_t>>,
          )
        >
      >('dort_run_options_create');
  late final _dort_run_options_create = _dort_run_options_createPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_runtime_t>,
          ffi.Pointer<ffi.Pointer<dort_run_options_t>>,
        )
      >();

  void dort_run_options_retain(ffi.Pointer<dort_run_options_t> options) {
    return _dort_run_options_retain(options);
  }

  late final _dort_run_options_retainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_options_t>)>
      >('dort_run_options_retain');
  late final _dort_run_options_retain = _dort_run_options_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_run_options_t>)>();

  void dort_run_options_release(ffi.Pointer<dort_run_options_t> options) {
    return _dort_run_options_release(options);
  }

  late final _dort_run_options_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_options_t>)>
      >('dort_run_options_release');
  late final _dort_run_options_release = _dort_run_options_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_run_options_t>)>();

  ffi.Pointer<dort_status_t> dort_run_options_set_terminate(
    ffi.Pointer<dort_run_options_t> options,
  ) {
    return _dort_run_options_set_terminate(options);
  }

  late final _dort_run_options_set_terminatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
        >
      >('dort_run_options_set_terminate');
  late final _dort_run_options_set_terminate =
      _dort_run_options_set_terminatePtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
          >();

  ffi.Pointer<dort_status_t> dort_run_options_unset_terminate(
    ffi.Pointer<dort_run_options_t> options,
  ) {
    return _dort_run_options_unset_terminate(options);
  }

  late final _dort_run_options_unset_terminatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
        >
      >('dort_run_options_unset_terminate');
  late final _dort_run_options_unset_terminate =
      _dort_run_options_unset_terminatePtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
          >();

  ffi.Pointer<dort_status_t> dort_run_options_profiling_start(
    ffi.Pointer<dort_run_options_t> options,
    ffi.Pointer<ffi.Char> artifact_root_utf8,
  ) {
    return _dort_run_options_profiling_start(options, artifact_root_utf8);
  }

  late final _dort_run_options_profiling_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_run_options_t>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('dort_run_options_profiling_start');
  late final _dort_run_options_profiling_start =
      _dort_run_options_profiling_startPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_run_options_t>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<dort_status_t> dort_run_options_profiling_finish(
    ffi.Pointer<dort_run_options_t> options,
    ffi.Pointer<dort_string_t> out_profile_json,
  ) {
    return _dort_run_options_profiling_finish(options, out_profile_json);
  }

  late final _dort_run_options_profiling_finishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_run_options_t>,
            ffi.Pointer<dort_string_t>,
          )
        >
      >('dort_run_options_profiling_finish');
  late final _dort_run_options_profiling_finish =
      _dort_run_options_profiling_finishPtr
          .asFunction<
            ffi.Pointer<dort_status_t> Function(
              ffi.Pointer<dort_run_options_t>,
              ffi.Pointer<dort_string_t>,
            )
          >();

  ffi.Pointer<dort_status_t> dort_cancel_token_register(
    ffi.Pointer<dort_run_options_t> run_options,
    ffi.Pointer<ffi.Uint64> out_token,
  ) {
    return _dort_cancel_token_register(run_options, out_token);
  }

  late final _dort_cancel_token_registerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_run_options_t>,
            ffi.Pointer<ffi.Uint64>,
          )
        >
      >('dort_cancel_token_register');
  late final _dort_cancel_token_register = _dort_cancel_token_registerPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_run_options_t>,
          ffi.Pointer<ffi.Uint64>,
        )
      >();

  ffi.Pointer<dort_status_t> dort_cancel_token_request(
    int token,
    ffi.Pointer<ffi.Uint32> out_did_request,
  ) {
    return _dort_cancel_token_request(token, out_did_request);
  }

  late final _dort_cancel_token_requestPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Uint64,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('dort_cancel_token_request');
  late final _dort_cancel_token_request = _dort_cancel_token_requestPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(int, ffi.Pointer<ffi.Uint32>)
      >();

  ffi.Pointer<dort_status_t> dort_cancel_token_finish(
    int token,
    ffi.Pointer<ffi.Uint32> out_was_requested,
  ) {
    return _dort_cancel_token_finish(token, out_was_requested);
  }

  late final _dort_cancel_token_finishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Uint64,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('dort_cancel_token_finish');
  late final _dort_cancel_token_finish = _dort_cancel_token_finishPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(int, ffi.Pointer<ffi.Uint32>)
      >();

  ffi.Pointer<dort_status_t> dort_session_run(
    ffi.Pointer<dort_session_t> session,
    ffi.Pointer<dort_run_options_t> run_options,
    ffi.Pointer<dort_named_value_t> inputs,
    int input_count,
    ffi.Pointer<ffi.Pointer<ffi.Char>> output_names_utf8,
    int output_count,
    ffi.Pointer<ffi.Pointer<dort_run_result_t>> out_result,
  ) {
    return _dort_session_run(
      session,
      run_options,
      inputs,
      input_count,
      output_names_utf8,
      output_count,
      out_result,
    );
  }

  late final _dort_session_runPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_session_t>,
            ffi.Pointer<dort_run_options_t>,
            ffi.Pointer<dort_named_value_t>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<dort_run_result_t>>,
          )
        >
      >('dort_session_run');
  late final _dort_session_run = _dort_session_runPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_session_t>,
          ffi.Pointer<dort_run_options_t>,
          ffi.Pointer<dort_named_value_t>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Pointer<dort_run_result_t>>,
        )
      >();

  void dort_run_result_retain(ffi.Pointer<dort_run_result_t> result) {
    return _dort_run_result_retain(result);
  }

  late final _dort_run_result_retainPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_result_t>)>
      >('dort_run_result_retain');
  late final _dort_run_result_retain = _dort_run_result_retainPtr
      .asFunction<void Function(ffi.Pointer<dort_run_result_t>)>();

  void dort_run_result_release(ffi.Pointer<dort_run_result_t> result) {
    return _dort_run_result_release(result);
  }

  late final _dort_run_result_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_result_t>)>
      >('dort_run_result_release');
  late final _dort_run_result_release = _dort_run_result_releasePtr
      .asFunction<void Function(ffi.Pointer<dort_run_result_t>)>();

  int dort_run_result_count(ffi.Pointer<dort_run_result_t> result) {
    return _dort_run_result_count(result);
  }

  late final _dort_run_result_countPtr =
      _lookup<
        ffi.NativeFunction<ffi.Size Function(ffi.Pointer<dort_run_result_t>)>
      >('dort_run_result_count');
  late final _dort_run_result_count = _dort_run_result_countPtr
      .asFunction<int Function(ffi.Pointer<dort_run_result_t>)>();

  ffi.Pointer<dort_status_t> dort_run_result_get(
    ffi.Pointer<dort_run_result_t> result,
    int index,
    ffi.Pointer<dort_string_t> out_name,
    ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
  ) {
    return _dort_run_result_get(result, index, out_name, out_value);
  }

  late final _dort_run_result_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dort_status_t> Function(
            ffi.Pointer<dort_run_result_t>,
            ffi.Size,
            ffi.Pointer<dort_string_t>,
            ffi.Pointer<ffi.Pointer<dort_value_t>>,
          )
        >
      >('dort_run_result_get');
  late final _dort_run_result_get = _dort_run_result_getPtr
      .asFunction<
        ffi.Pointer<dort_status_t> Function(
          ffi.Pointer<dort_run_result_t>,
          int,
          ffi.Pointer<dort_string_t>,
          ffi.Pointer<ffi.Pointer<dort_value_t>>,
        )
      >();
}

final class dort_status extends ffi.Opaque {}

typedef dort_status_t = dort_status;

final class dort_runtime extends ffi.Opaque {}

typedef dort_runtime_t = dort_runtime;

final class dort_session_options extends ffi.Opaque {}

typedef dort_session_options_t = dort_session_options;

final class dort_session extends ffi.Opaque {}

typedef dort_session_t = dort_session;

final class dort_run_options extends ffi.Opaque {}

typedef dort_run_options_t = dort_run_options;

final class dort_buffer extends ffi.Opaque {}

typedef dort_buffer_t = dort_buffer;

final class dort_value extends ffi.Opaque {}

typedef dort_value_t = dort_value;

final class dort_run_result extends ffi.Opaque {}

typedef dort_run_result_t = dort_run_result;

final class dort_data_lease extends ffi.Opaque {}

typedef dort_data_lease_t = dort_data_lease;

enum dort_runtime_source_kind {
  DORT_RUNTIME_SOURCE_LINKED(1),
  DORT_RUNTIME_SOURCE_BUNDLED(2),
  DORT_RUNTIME_SOURCE_PROCESS(3),
  DORT_RUNTIME_SOURCE_FILE(4);

  final int value;
  const dort_runtime_source_kind(this.value);

  static dort_runtime_source_kind fromValue(int value) => switch (value) {
    1 => DORT_RUNTIME_SOURCE_LINKED,
    2 => DORT_RUNTIME_SOURCE_BUNDLED,
    3 => DORT_RUNTIME_SOURCE_PROCESS,
    4 => DORT_RUNTIME_SOURCE_FILE,
    _ => throw ArgumentError(
      'Unknown value for dort_runtime_source_kind: $value',
    ),
  };
}

enum dort_log_severity {
  DORT_LOG_VERBOSE(0),
  DORT_LOG_INFO(1),
  DORT_LOG_WARNING(2),
  DORT_LOG_ERROR(3),
  DORT_LOG_FATAL(4);

  final int value;
  const dort_log_severity(this.value);

  static dort_log_severity fromValue(int value) => switch (value) {
    0 => DORT_LOG_VERBOSE,
    1 => DORT_LOG_INFO,
    2 => DORT_LOG_WARNING,
    3 => DORT_LOG_ERROR,
    4 => DORT_LOG_FATAL,
    _ => throw ArgumentError('Unknown value for dort_log_severity: $value'),
  };
}

enum dort_error_domain {
  DORT_ERROR_DOMAIN_NONE(0),
  DORT_ERROR_DOMAIN_SHIM(1),
  DORT_ERROR_DOMAIN_LOADER(2),
  DORT_ERROR_DOMAIN_ORT_API(3),
  DORT_ERROR_DOMAIN_ALLOCATION(4),
  DORT_ERROR_DOMAIN_UNSUPPORTED(5),
  DORT_ERROR_DOMAIN_ORT_STATUS(6),
  DORT_ERROR_DOMAIN_PROVIDER(7);

  final int value;
  const dort_error_domain(this.value);

  static dort_error_domain fromValue(int value) => switch (value) {
    0 => DORT_ERROR_DOMAIN_NONE,
    1 => DORT_ERROR_DOMAIN_SHIM,
    2 => DORT_ERROR_DOMAIN_LOADER,
    3 => DORT_ERROR_DOMAIN_ORT_API,
    4 => DORT_ERROR_DOMAIN_ALLOCATION,
    5 => DORT_ERROR_DOMAIN_UNSUPPORTED,
    6 => DORT_ERROR_DOMAIN_ORT_STATUS,
    7 => DORT_ERROR_DOMAIN_PROVIDER,
    _ => throw ArgumentError('Unknown value for dort_error_domain: $value'),
  };
}

enum dort_error_code {
  DORT_ERROR_NONE(0),
  DORT_ERROR_INVALID_ARGUMENT(1),
  DORT_ERROR_ABI_MISMATCH(2),
  DORT_ERROR_API_REQUEST_UNSUPPORTED(3),
  DORT_ERROR_SOURCE_UNSUPPORTED(4),
  DORT_ERROR_PATH_NOT_ABSOLUTE(5),
  DORT_ERROR_PATH_OUTSIDE_ALLOWED_ROOT(6),
  DORT_ERROR_RUNTIME_NOT_FOUND(7),
  DORT_ERROR_SYMBOL_NOT_FOUND(8),
  DORT_ERROR_ORT_API_UNAVAILABLE(9),
  DORT_ERROR_ALLOCATION_FAILED(10),
  DORT_ERROR_INVALID_UTF8(11),
  DORT_ERROR_LIMIT_EXCEEDED(12),
  DORT_ERROR_PLATFORM(13),
  DORT_ERROR_RUNTIME_IDENTITY_MISMATCH(14),
  DORT_ERROR_MODEL_INVALID(15),
  DORT_ERROR_TENSOR_INVALID(16),
  DORT_ERROR_RUN_FAILED(17),
  DORT_ERROR_BUFFER_TOO_SMALL(18),
  DORT_ERROR_OVERFLOW(19),
  DORT_ERROR_PROVIDER_UNSUPPORTED(20),
  DORT_ERROR_NOT_TENSOR(21),
  DORT_ERROR_VALUE_KIND_UNSUPPORTED(22),
  DORT_ERROR_NOT_COMPOSITE(23),
  DORT_ERROR_DATA_LEASE_UNSUPPORTED(24),
  DORT_ERROR_MEMORY_DOMAIN_UNSUPPORTED(25),
  DORT_ERROR_EXTERNAL_DATA_INVALID(26),
  DORT_ERROR_CANCEL_TOKEN_UNKNOWN(27),
  DORT_ERROR_CANCEL_REGISTRY_FULL(28);

  final int value;
  const dort_error_code(this.value);

  static dort_error_code fromValue(int value) => switch (value) {
    0 => DORT_ERROR_NONE,
    1 => DORT_ERROR_INVALID_ARGUMENT,
    2 => DORT_ERROR_ABI_MISMATCH,
    3 => DORT_ERROR_API_REQUEST_UNSUPPORTED,
    4 => DORT_ERROR_SOURCE_UNSUPPORTED,
    5 => DORT_ERROR_PATH_NOT_ABSOLUTE,
    6 => DORT_ERROR_PATH_OUTSIDE_ALLOWED_ROOT,
    7 => DORT_ERROR_RUNTIME_NOT_FOUND,
    8 => DORT_ERROR_SYMBOL_NOT_FOUND,
    9 => DORT_ERROR_ORT_API_UNAVAILABLE,
    10 => DORT_ERROR_ALLOCATION_FAILED,
    11 => DORT_ERROR_INVALID_UTF8,
    12 => DORT_ERROR_LIMIT_EXCEEDED,
    13 => DORT_ERROR_PLATFORM,
    14 => DORT_ERROR_RUNTIME_IDENTITY_MISMATCH,
    15 => DORT_ERROR_MODEL_INVALID,
    16 => DORT_ERROR_TENSOR_INVALID,
    17 => DORT_ERROR_RUN_FAILED,
    18 => DORT_ERROR_BUFFER_TOO_SMALL,
    19 => DORT_ERROR_OVERFLOW,
    20 => DORT_ERROR_PROVIDER_UNSUPPORTED,
    21 => DORT_ERROR_NOT_TENSOR,
    22 => DORT_ERROR_VALUE_KIND_UNSUPPORTED,
    23 => DORT_ERROR_NOT_COMPOSITE,
    24 => DORT_ERROR_DATA_LEASE_UNSUPPORTED,
    25 => DORT_ERROR_MEMORY_DOMAIN_UNSUPPORTED,
    26 => DORT_ERROR_EXTERNAL_DATA_INVALID,
    27 => DORT_ERROR_CANCEL_TOKEN_UNKNOWN,
    28 => DORT_ERROR_CANCEL_REGISTRY_FULL,
    _ => throw ArgumentError('Unknown value for dort_error_code: $value'),
  };
}

enum dort_graph_optimization_level {
  DORT_GRAPH_OPTIMIZATION_DISABLED(0),
  DORT_GRAPH_OPTIMIZATION_BASIC(1),
  DORT_GRAPH_OPTIMIZATION_EXTENDED(2),
  DORT_GRAPH_OPTIMIZATION_ALL(3);

  final int value;
  const dort_graph_optimization_level(this.value);

  static dort_graph_optimization_level fromValue(int value) => switch (value) {
    0 => DORT_GRAPH_OPTIMIZATION_DISABLED,
    1 => DORT_GRAPH_OPTIMIZATION_BASIC,
    2 => DORT_GRAPH_OPTIMIZATION_EXTENDED,
    3 => DORT_GRAPH_OPTIMIZATION_ALL,
    _ => throw ArgumentError(
      'Unknown value for dort_graph_optimization_level: $value',
    ),
  };
}

enum dort_execution_mode {
  DORT_EXECUTION_SEQUENTIAL(0),
  DORT_EXECUTION_PARALLEL(1);

  final int value;
  const dort_execution_mode(this.value);

  static dort_execution_mode fromValue(int value) => switch (value) {
    0 => DORT_EXECUTION_SEQUENTIAL,
    1 => DORT_EXECUTION_PARALLEL,
    _ => throw ArgumentError('Unknown value for dort_execution_mode: $value'),
  };
}

enum dort_tensor_element_type {
  DORT_TENSOR_FLOAT32(1),
  DORT_TENSOR_UINT8(2),
  DORT_TENSOR_INT8(3),
  DORT_TENSOR_UINT16(4),
  DORT_TENSOR_INT16(5),
  DORT_TENSOR_INT32(6),
  DORT_TENSOR_INT64(7),
  DORT_TENSOR_STRING(8),
  DORT_TENSOR_BOOL(9),
  DORT_TENSOR_FLOAT16(10),
  DORT_TENSOR_FLOAT64(11),
  DORT_TENSOR_UINT32(12),
  DORT_TENSOR_UINT64(13),
  DORT_TENSOR_BFLOAT16(16);

  final int value;
  const dort_tensor_element_type(this.value);

  static dort_tensor_element_type fromValue(int value) => switch (value) {
    1 => DORT_TENSOR_FLOAT32,
    2 => DORT_TENSOR_UINT8,
    3 => DORT_TENSOR_INT8,
    4 => DORT_TENSOR_UINT16,
    5 => DORT_TENSOR_INT16,
    6 => DORT_TENSOR_INT32,
    7 => DORT_TENSOR_INT64,
    8 => DORT_TENSOR_STRING,
    9 => DORT_TENSOR_BOOL,
    10 => DORT_TENSOR_FLOAT16,
    11 => DORT_TENSOR_FLOAT64,
    12 => DORT_TENSOR_UINT32,
    13 => DORT_TENSOR_UINT64,
    16 => DORT_TENSOR_BFLOAT16,
    _ => throw ArgumentError(
      'Unknown value for dort_tensor_element_type: $value',
    ),
  };
}

enum dort_value_kind {
  DORT_VALUE_KIND_TENSOR(1),
  DORT_VALUE_KIND_SEQUENCE(2),
  DORT_VALUE_KIND_MAP(3),
  DORT_VALUE_KIND_OPTIONAL(6);

  final int value;
  const dort_value_kind(this.value);

  static dort_value_kind fromValue(int value) => switch (value) {
    1 => DORT_VALUE_KIND_TENSOR,
    2 => DORT_VALUE_KIND_SEQUENCE,
    3 => DORT_VALUE_KIND_MAP,
    6 => DORT_VALUE_KIND_OPTIONAL,
    _ => throw ArgumentError('Unknown value for dort_value_kind: $value'),
  };
}

final class dort_string extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int length;

  external ffi.Pointer<ffi.Void> private_owner;
}

typedef dort_string_t = dort_string;

final class dort_runtime_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int shim_abi_version;

  @ffi.Uint32()
  external int required_ort_api_version;

  @ffi.Uint32()
  external int source_kind;

  @ffi.Uint32()
  external int flags;

  @ffi.Uint32()
  external int log_severity;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> log_id_utf8;

  external ffi.Pointer<ffi.Char> library_path_utf8;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> preferred_library_names_utf8;

  @ffi.Size()
  external int preferred_library_name_count;

  external ffi.Pointer<ffi.Char> allowed_root_utf8;
}

typedef dort_runtime_config_t = dort_runtime_config;

final class dort_string_pair extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> key_utf8;

  external ffi.Pointer<ffi.Char> value_utf8;
}

typedef dort_string_pair_t = dort_string_pair;

final class dort_provider_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> provider_id_utf8;

  external ffi.Pointer<dort_string_pair_t> options;

  @ffi.Size()
  external int option_count;
}

typedef dort_provider_config_t = dort_provider_config;

final class dort_session_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int graph_optimization_level;

  @ffi.Uint32()
  external int execution_mode;

  @ffi.Int32()
  external int intra_op_thread_count;

  @ffi.Int32()
  external int inter_op_thread_count;

  @ffi.Uint32()
  external int enable_cpu_memory_arena;

  @ffi.Uint32()
  external int enable_memory_pattern;

  @ffi.Uint32()
  external int deterministic_compute;

  @ffi.Uint32()
  external int enable_profiling;

  @ffi.Uint32()
  external int log_severity;

  @ffi.Int32()
  external int log_verbosity;

  @ffi.Uint32()
  external int optimized_model_overwrite;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> log_id_utf8;

  external ffi.Pointer<ffi.Char> profile_path_prefix_utf8;

  external ffi.Pointer<ffi.Char> optimized_model_path_utf8;

  external ffi.Pointer<ffi.Char> artifact_root_utf8;

  @ffi.Size()
  external int max_model_bytes;

  external ffi.Pointer<dort_provider_config_t> providers;

  @ffi.Size()
  external int provider_count;

  external ffi.Pointer<dort_string_pair_t> config_entries;

  @ffi.Size()
  external int config_entry_count;
}

typedef dort_session_config_t = dort_session_config;

final class dort_named_value extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> name_utf8;

  external ffi.Pointer<dort_value_t> value;
}

typedef dort_named_value_t = dort_named_value;

final class dort_utf8_span extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int length;
}

typedef dort_utf8_span_t = dort_utf8_span;

final class dort_external_data extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Uint8> relative_name_utf8;

  @ffi.Size()
  external int relative_name_length;

  external ffi.Pointer<ffi.Void> data;

  @ffi.Size()
  external int data_length;
}

typedef dort_external_data_t = dort_external_data;

const int DORT_ABI_VERSION = 1;

const int DORT_ORT_API_COMPATIBILITY_FLOOR = 27;
