// Regenerate with: dart run ffigen --config ffigen.native_assets.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:fonix/fonix_shim')
library;

import 'dart:ffi' as ffi;
import '' as self;

@ffi.Native<ffi.Uint32 Function()>()
external int dort_get_abi_version();

@ffi.Native<ffi.Uint32 Function()>()
external int dort_get_ort_api_compatibility_floor();

@ffi.Native<ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_string_t>)>()
external ffi.Pointer<dort_status_t> dort_get_build_manifest_json(
  ffi.Pointer<dort_string_t> out_json,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_string_t>)>()
external void dort_string_release(ffi.Pointer<dort_string_t> string_value);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<dort_status_t>)>()
external int dort_status_domain(ffi.Pointer<dort_status_t> status);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<dort_status_t>)>()
external int dort_status_code(ffi.Pointer<dort_status_t> status);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<dort_status_t>)>()
external int dort_status_ort_code(ffi.Pointer<dort_status_t> status);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)>()
external ffi.Pointer<ffi.Char> dort_status_operation(
  ffi.Pointer<dort_status_t> status,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)>()
external ffi.Pointer<ffi.Char> dort_status_message(
  ffi.Pointer<dort_status_t> status,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_status_t>)>()
external void dort_status_release(ffi.Pointer<dort_status_t> status);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_config_t>,
    ffi.Pointer<ffi.Pointer<dort_runtime_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_runtime_open(
  ffi.Pointer<dort_runtime_config_t> config,
  ffi.Pointer<ffi.Pointer<dort_runtime_t>> out_runtime,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_runtime_t>)>()
external void dort_runtime_retain(ffi.Pointer<dort_runtime_t> runtime);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_runtime_t>)>()
external void dort_runtime_release(ffi.Pointer<dort_runtime_t> runtime);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_runtime_info_json(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_string_t> out_json,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_runtime_available_providers_json(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_string_t> out_json,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_session_config_t>,
    ffi.Pointer<ffi.Pointer<dort_session_options_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_session_options_create(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_session_config_t> config,
  ffi.Pointer<ffi.Pointer<dort_session_options_t>> out_options,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_session_options_t>)>()
external void dort_session_options_retain(
  ffi.Pointer<dort_session_options_t> options,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_session_options_t>)>()
external void dort_session_options_release(
  ffi.Pointer<dort_session_options_t> options,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_session_options_t>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<dort_session_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_session_create_from_bytes(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_session_options_t> options,
  ffi.Pointer<ffi.Void> model_data,
  int model_data_length,
  ffi.Pointer<ffi.Pointer<dort_session_t>> out_session,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_session_options_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<dort_session_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_session_create_from_file(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_session_options_t> options,
  ffi.Pointer<ffi.Char> model_path_utf8,
  ffi.Pointer<ffi.Char> allowed_root_utf8,
  ffi.Pointer<ffi.Pointer<dort_session_t>> out_session,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_session_options_t>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<dort_external_data_t>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<dort_session_t>>,
  )
>()
external ffi.Pointer<dort_status_t>
dort_session_create_from_bytes_with_external_data(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_session_options_t> options,
  ffi.Pointer<ffi.Void> model_data,
  int model_data_length,
  ffi.Pointer<dort_external_data_t> external_data,
  int external_data_count,
  ffi.Pointer<ffi.Pointer<dort_session_t>> out_session,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_session_t>)>()
external void dort_session_retain(ffi.Pointer<dort_session_t> session);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_session_t>)>()
external void dort_session_release(ffi.Pointer<dort_session_t> session);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_session_t>,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_session_metadata_json(
  ffi.Pointer<dort_session_t> session,
  ffi.Pointer<dort_string_t> out_json,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_session_t>,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_session_type_metadata_json(
  ffi.Pointer<dort_session_t> session,
  ffi.Pointer<dort_string_t> out_json,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_session_t>,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_session_model_metadata_json(
  ffi.Pointer<dort_session_t> session,
  ffi.Pointer<dort_string_t> out_json,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<dort_buffer_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_buffer_allocate(
  ffi.Pointer<dort_runtime_t> runtime,
  int byte_length,
  int alignment,
  ffi.Pointer<ffi.Pointer<dort_buffer_t>> out_buffer,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_buffer_t>)>()
external void dort_buffer_retain(ffi.Pointer<dort_buffer_t> buffer);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_buffer_t>)>()
external void dort_buffer_release(ffi.Pointer<dort_buffer_t> buffer);

@ffi.Native<ffi.Size Function(ffi.Pointer<dort_buffer_t>)>()
external int dort_buffer_byte_length(ffi.Pointer<dort_buffer_t> buffer);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_buffer_t>,
    ffi.Size,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external ffi.Pointer<dort_status_t> dort_buffer_write(
  ffi.Pointer<dort_buffer_t> buffer,
  int offset,
  ffi.Pointer<ffi.Void> source,
  int byte_length,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_buffer_t>,
    ffi.Size,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external ffi.Pointer<dort_status_t> dort_buffer_read(
  ffi.Pointer<dort_buffer_t> buffer,
  int offset,
  ffi.Pointer<ffi.Void> destination,
  int byte_length,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_buffer_t>,
    ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external ffi.Pointer<dort_status_t> dort_buffer_data_acquire(
  ffi.Pointer<dort_buffer_t> buffer,
  ffi.Pointer<ffi.Pointer<dort_data_lease_t>> out_lease,
  ffi.Pointer<ffi.Pointer<ffi.Void>> out_data,
  ffi.Pointer<ffi.Size> out_byte_length,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<ffi.Int64>,
    ffi.Size,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_create_copy(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<ffi.Void> data,
  int byte_length,
  ffi.Pointer<ffi.Int64> dimensions,
  int dimension_count,
  int element_type,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_buffer_t>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Int64>,
    ffi.Size,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_create_with_buffer(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_buffer_t> buffer,
  int byte_offset,
  int byte_length,
  ffi.Pointer<ffi.Int64> dimensions,
  int dimension_count,
  int element_type,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_utf8_span_t>,
    ffi.Size,
    ffi.Pointer<ffi.Int64>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_create_strings_copy(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_utf8_span_t> strings,
  int string_count,
  ffi.Pointer<ffi.Int64> dimensions,
  int dimension_count,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_value_t>)>()
external void dort_value_retain(ffi.Pointer<dort_value_t> value);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_value_t>)>()
external void dort_value_release(ffi.Pointer<dort_value_t> value);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<ffi.Uint32>,
  )
>(symbol: 'dort_value_kind')
external ffi.Pointer<dort_status_t> dort_value_kind$1(
  ffi.Pointer<dort_value_t> value,
  ffi.Pointer<ffi.Uint32> out_kind,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<ffi.Size>,
  )
>()
external ffi.Pointer<dort_status_t> dort_value_child_count(
  ffi.Pointer<dort_value_t> value,
  ffi.Pointer<ffi.Size> out_count,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_value_child_get(
  ffi.Pointer<dort_value_t> value,
  int index,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_child,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_sequence_create(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<ffi.Pointer<dort_value_t>> values,
  int value_count,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_map_create(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<dort_value_t> keys,
  ffi.Pointer<dort_value_t> values,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_optional_none_create(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_optional_some_create(
  ffi.Pointer<dort_value_t> contained_value,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_info_json(
  ffi.Pointer<dort_value_t> value,
  ffi.Pointer<dort_string_t> out_json,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_copy_data(
  ffi.Pointer<dort_value_t> value,
  ffi.Pointer<ffi.Void> destination,
  int destination_capacity,
  ffi.Pointer<ffi.Size> out_required_bytes,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<ffi.Size>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_string_count(
  ffi.Pointer<dort_value_t> value,
  ffi.Pointer<ffi.Size> out_count,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Size,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_string_get(
  ffi.Pointer<dort_value_t> value,
  int index,
  ffi.Pointer<dort_string_t> out_string,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_value_t>,
    ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external ffi.Pointer<dort_status_t> dort_tensor_data_acquire(
  ffi.Pointer<dort_value_t> value,
  ffi.Pointer<ffi.Pointer<dort_data_lease_t>> out_lease,
  ffi.Pointer<ffi.Pointer<ffi.Void>> out_data,
  ffi.Pointer<ffi.Size> out_byte_length,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_data_lease_t>)>()
external void dort_data_lease_retain(ffi.Pointer<dort_data_lease_t> lease);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_data_lease_t>)>()
external void dort_data_lease_release(ffi.Pointer<dort_data_lease_t> lease);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_runtime_t>,
    ffi.Pointer<ffi.Pointer<dort_run_options_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_run_options_create(
  ffi.Pointer<dort_runtime_t> runtime,
  ffi.Pointer<ffi.Pointer<dort_run_options_t>> out_options,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_run_options_t>)>()
external void dort_run_options_retain(ffi.Pointer<dort_run_options_t> options);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_run_options_t>)>()
external void dort_run_options_release(ffi.Pointer<dort_run_options_t> options);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
>()
external ffi.Pointer<dort_status_t> dort_run_options_set_terminate(
  ffi.Pointer<dort_run_options_t> options,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
>()
external ffi.Pointer<dort_status_t> dort_run_options_unset_terminate(
  ffi.Pointer<dort_run_options_t> options,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_run_options_t>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<dort_status_t> dort_run_options_profiling_start(
  ffi.Pointer<dort_run_options_t> options,
  ffi.Pointer<ffi.Char> artifact_root_utf8,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_run_options_t>,
    ffi.Pointer<dort_string_t>,
  )
>()
external ffi.Pointer<dort_status_t> dort_run_options_profiling_finish(
  ffi.Pointer<dort_run_options_t> options,
  ffi.Pointer<dort_string_t> out_profile_json,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_run_options_t>,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external ffi.Pointer<dort_status_t> dort_cancel_token_register(
  ffi.Pointer<dort_run_options_t> run_options,
  ffi.Pointer<ffi.Uint64> out_token,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(ffi.Uint64, ffi.Pointer<ffi.Uint32>)
>()
external ffi.Pointer<dort_status_t> dort_cancel_token_request(
  int token,
  ffi.Pointer<ffi.Uint32> out_did_request,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(ffi.Uint64, ffi.Pointer<ffi.Uint32>)
>()
external ffi.Pointer<dort_status_t> dort_cancel_token_finish(
  int token,
  ffi.Pointer<ffi.Uint32> out_was_requested,
);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_session_t>,
    ffi.Pointer<dort_run_options_t>,
    ffi.Pointer<dort_named_value_t>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<dort_run_result_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_session_run(
  ffi.Pointer<dort_session_t> session,
  ffi.Pointer<dort_run_options_t> run_options,
  ffi.Pointer<dort_named_value_t> inputs,
  int input_count,
  ffi.Pointer<ffi.Pointer<ffi.Char>> output_names_utf8,
  int output_count,
  ffi.Pointer<ffi.Pointer<dort_run_result_t>> out_result,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_run_result_t>)>()
external void dort_run_result_retain(ffi.Pointer<dort_run_result_t> result);

@ffi.Native<ffi.Void Function(ffi.Pointer<dort_run_result_t>)>()
external void dort_run_result_release(ffi.Pointer<dort_run_result_t> result);

@ffi.Native<ffi.Size Function(ffi.Pointer<dort_run_result_t>)>()
external int dort_run_result_count(ffi.Pointer<dort_run_result_t> result);

@ffi.Native<
  ffi.Pointer<dort_status_t> Function(
    ffi.Pointer<dort_run_result_t>,
    ffi.Size,
    ffi.Pointer<dort_string_t>,
    ffi.Pointer<ffi.Pointer<dort_value_t>>,
  )
>()
external ffi.Pointer<dort_status_t> dort_run_result_get(
  ffi.Pointer<dort_run_result_t> result,
  int index,
  ffi.Pointer<dort_string_t> out_name,
  ffi.Pointer<ffi.Pointer<dort_value_t>> out_value,
);

const addresses = _SymbolAddresses();

class _SymbolAddresses {
  const _SymbolAddresses();
  ffi.Pointer<ffi.NativeFunction<ffi.Uint32 Function()>>
  get dort_get_abi_version => ffi.Native.addressOf(self.dort_get_abi_version);
  ffi.Pointer<ffi.NativeFunction<ffi.Uint32 Function()>>
  get dort_get_ort_api_compatibility_floor =>
      ffi.Native.addressOf(self.dort_get_ort_api_compatibility_floor);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_string_t>)
    >
  >
  get dort_get_build_manifest_json =>
      ffi.Native.addressOf(self.dort_get_build_manifest_json);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_string_t>)>>
  get dort_string_release => ffi.Native.addressOf(self.dort_string_release);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dort_status_t>)>
  >
  get dort_status_domain => ffi.Native.addressOf(self.dort_status_domain);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dort_status_t>)>
  >
  get dort_status_code => ffi.Native.addressOf(self.dort_status_code);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dort_status_t>)>
  >
  get dort_status_ort_code => ffi.Native.addressOf(self.dort_status_ort_code);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)
    >
  >
  get dort_status_operation => ffi.Native.addressOf(self.dort_status_operation);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<dort_status_t>)
    >
  >
  get dort_status_message => ffi.Native.addressOf(self.dort_status_message);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_status_t>)>>
  get dort_status_release => ffi.Native.addressOf(self.dort_status_release);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_config_t>,
        ffi.Pointer<ffi.Pointer<dort_runtime_t>>,
      )
    >
  >
  get dort_runtime_open => ffi.Native.addressOf(self.dort_runtime_open);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_runtime_t>)>
  >
  get dort_runtime_retain => ffi.Native.addressOf(self.dort_runtime_retain);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_runtime_t>)>
  >
  get dort_runtime_release => ffi.Native.addressOf(self.dort_runtime_release);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_runtime_info_json =>
      ffi.Native.addressOf(self.dort_runtime_info_json);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_runtime_available_providers_json =>
      ffi.Native.addressOf(self.dort_runtime_available_providers_json);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_session_config_t>,
        ffi.Pointer<ffi.Pointer<dort_session_options_t>>,
      )
    >
  >
  get dort_session_options_create =>
      ffi.Native.addressOf(self.dort_session_options_create);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_session_options_t>)>
  >
  get dort_session_options_retain =>
      ffi.Native.addressOf(self.dort_session_options_retain);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_session_options_t>)>
  >
  get dort_session_options_release =>
      ffi.Native.addressOf(self.dort_session_options_release);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_session_options_t>,
        ffi.Pointer<ffi.Void>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<dort_session_t>>,
      )
    >
  >
  get dort_session_create_from_bytes =>
      ffi.Native.addressOf(self.dort_session_create_from_bytes);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_session_options_t>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<dort_session_t>>,
      )
    >
  >
  get dort_session_create_from_file =>
      ffi.Native.addressOf(self.dort_session_create_from_file);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_session_options_t>,
        ffi.Pointer<ffi.Void>,
        ffi.Size,
        ffi.Pointer<dort_external_data_t>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<dort_session_t>>,
      )
    >
  >
  get dort_session_create_from_bytes_with_external_data => ffi.Native.addressOf(
    self.dort_session_create_from_bytes_with_external_data,
  );
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_session_t>)>
  >
  get dort_session_retain => ffi.Native.addressOf(self.dort_session_retain);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_session_t>)>
  >
  get dort_session_release => ffi.Native.addressOf(self.dort_session_release);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_session_t>,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_session_metadata_json =>
      ffi.Native.addressOf(self.dort_session_metadata_json);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_session_t>,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_session_type_metadata_json =>
      ffi.Native.addressOf(self.dort_session_type_metadata_json);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_session_t>,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_session_model_metadata_json =>
      ffi.Native.addressOf(self.dort_session_model_metadata_json);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Size,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<dort_buffer_t>>,
      )
    >
  >
  get dort_buffer_allocate => ffi.Native.addressOf(self.dort_buffer_allocate);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_buffer_t>)>>
  get dort_buffer_retain => ffi.Native.addressOf(self.dort_buffer_retain);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_buffer_t>)>>
  get dort_buffer_release => ffi.Native.addressOf(self.dort_buffer_release);
  ffi.Pointer<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<dort_buffer_t>)>>
  get dort_buffer_byte_length =>
      ffi.Native.addressOf(self.dort_buffer_byte_length);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_buffer_t>,
        ffi.Size,
        ffi.Pointer<ffi.Void>,
        ffi.Size,
      )
    >
  >
  get dort_buffer_write => ffi.Native.addressOf(self.dort_buffer_write);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_buffer_t>,
        ffi.Size,
        ffi.Pointer<ffi.Void>,
        ffi.Size,
      )
    >
  >
  get dort_buffer_read => ffi.Native.addressOf(self.dort_buffer_read);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_buffer_t>,
        ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
        ffi.Pointer<ffi.Pointer<ffi.Void>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get dort_buffer_data_acquire =>
      ffi.Native.addressOf(self.dort_buffer_data_acquire);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<ffi.Void>,
        ffi.Size,
        ffi.Pointer<ffi.Int64>,
        ffi.Size,
        ffi.Uint32,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_tensor_create_copy =>
      ffi.Native.addressOf(self.dort_tensor_create_copy);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_buffer_t>,
        ffi.Size,
        ffi.Size,
        ffi.Pointer<ffi.Int64>,
        ffi.Size,
        ffi.Uint32,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_tensor_create_with_buffer =>
      ffi.Native.addressOf(self.dort_tensor_create_with_buffer);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_utf8_span_t>,
        ffi.Size,
        ffi.Pointer<ffi.Int64>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_tensor_create_strings_copy =>
      ffi.Native.addressOf(self.dort_tensor_create_strings_copy);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_value_t>)>>
  get dort_value_retain => ffi.Native.addressOf(self.dort_value_retain);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_value_t>)>>
  get dort_value_release => ffi.Native.addressOf(self.dort_value_release);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<ffi.Uint32>,
      )
    >
  >
  get dort_value_kind$1 => ffi.Native.addressOf(self.dort_value_kind$1);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get dort_value_child_count =>
      ffi.Native.addressOf(self.dort_value_child_count);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_value_child_get => ffi.Native.addressOf(self.dort_value_child_get);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_sequence_create => ffi.Native.addressOf(self.dort_sequence_create);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_map_create => ffi.Native.addressOf(self.dort_map_create);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_optional_none_create =>
      ffi.Native.addressOf(self.dort_optional_none_create);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_optional_some_create =>
      ffi.Native.addressOf(self.dort_optional_some_create);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_tensor_info_json => ffi.Native.addressOf(self.dort_tensor_info_json);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<ffi.Void>,
        ffi.Size,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get dort_tensor_copy_data => ffi.Native.addressOf(self.dort_tensor_copy_data);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get dort_tensor_string_count =>
      ffi.Native.addressOf(self.dort_tensor_string_count);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Size,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_tensor_string_get =>
      ffi.Native.addressOf(self.dort_tensor_string_get);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_value_t>,
        ffi.Pointer<ffi.Pointer<dort_data_lease_t>>,
        ffi.Pointer<ffi.Pointer<ffi.Void>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get dort_tensor_data_acquire =>
      ffi.Native.addressOf(self.dort_tensor_data_acquire);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_data_lease_t>)>
  >
  get dort_data_lease_retain =>
      ffi.Native.addressOf(self.dort_data_lease_retain);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_data_lease_t>)>
  >
  get dort_data_lease_release =>
      ffi.Native.addressOf(self.dort_data_lease_release);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_runtime_t>,
        ffi.Pointer<ffi.Pointer<dort_run_options_t>>,
      )
    >
  >
  get dort_run_options_create =>
      ffi.Native.addressOf(self.dort_run_options_create);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_options_t>)>
  >
  get dort_run_options_retain =>
      ffi.Native.addressOf(self.dort_run_options_retain);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_options_t>)>
  >
  get dort_run_options_release =>
      ffi.Native.addressOf(self.dort_run_options_release);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
    >
  >
  get dort_run_options_set_terminate =>
      ffi.Native.addressOf(self.dort_run_options_set_terminate);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(ffi.Pointer<dort_run_options_t>)
    >
  >
  get dort_run_options_unset_terminate =>
      ffi.Native.addressOf(self.dort_run_options_unset_terminate);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_run_options_t>,
        ffi.Pointer<ffi.Char>,
      )
    >
  >
  get dort_run_options_profiling_start =>
      ffi.Native.addressOf(self.dort_run_options_profiling_start);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_run_options_t>,
        ffi.Pointer<dort_string_t>,
      )
    >
  >
  get dort_run_options_profiling_finish =>
      ffi.Native.addressOf(self.dort_run_options_profiling_finish);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_run_options_t>,
        ffi.Pointer<ffi.Uint64>,
      )
    >
  >
  get dort_cancel_token_register =>
      ffi.Native.addressOf(self.dort_cancel_token_register);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(ffi.Uint64, ffi.Pointer<ffi.Uint32>)
    >
  >
  get dort_cancel_token_request =>
      ffi.Native.addressOf(self.dort_cancel_token_request);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(ffi.Uint64, ffi.Pointer<ffi.Uint32>)
    >
  >
  get dort_cancel_token_finish =>
      ffi.Native.addressOf(self.dort_cancel_token_finish);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_session_t>,
        ffi.Pointer<dort_run_options_t>,
        ffi.Pointer<dort_named_value_t>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<dort_run_result_t>>,
      )
    >
  >
  get dort_session_run => ffi.Native.addressOf(self.dort_session_run);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_result_t>)>
  >
  get dort_run_result_retain =>
      ffi.Native.addressOf(self.dort_run_result_retain);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dort_run_result_t>)>
  >
  get dort_run_result_release =>
      ffi.Native.addressOf(self.dort_run_result_release);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Size Function(ffi.Pointer<dort_run_result_t>)>
  >
  get dort_run_result_count => ffi.Native.addressOf(self.dort_run_result_count);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<dort_status_t> Function(
        ffi.Pointer<dort_run_result_t>,
        ffi.Size,
        ffi.Pointer<dort_string_t>,
        ffi.Pointer<ffi.Pointer<dort_value_t>>,
      )
    >
  >
  get dort_run_result_get => ffi.Native.addressOf(self.dort_run_result_get);
}

final class dort_status extends ffi.Opaque {}

typedef dort_status_t = dort_status;

final class dort_runtime extends ffi.Opaque {}

typedef dort_runtime_t = dort_runtime;

final class dort_session_options extends ffi.Opaque {}

typedef dort_session_options_t = dort_session_options;

final class dort_session extends ffi.Opaque {}

typedef dort_session_t = dort_session;

final class dort_run_options extends ffi.Opaque {}

typedef dort_run_options_t = dort_run_options;

final class dort_buffer extends ffi.Opaque {}

typedef dort_buffer_t = dort_buffer;

final class dort_value extends ffi.Opaque {}

typedef dort_value_t = dort_value;

final class dort_run_result extends ffi.Opaque {}

typedef dort_run_result_t = dort_run_result;

final class dort_data_lease extends ffi.Opaque {}

typedef dort_data_lease_t = dort_data_lease;

sealed class dort_runtime_source_kind {
  static const DORT_RUNTIME_SOURCE_LINKED = 1;
  static const DORT_RUNTIME_SOURCE_BUNDLED = 2;
  static const DORT_RUNTIME_SOURCE_PROCESS = 3;
  static const DORT_RUNTIME_SOURCE_FILE = 4;
}

sealed class dort_log_severity {
  static const DORT_LOG_VERBOSE = 0;
  static const DORT_LOG_INFO = 1;
  static const DORT_LOG_WARNING = 2;
  static const DORT_LOG_ERROR = 3;
  static const DORT_LOG_FATAL = 4;
}

sealed class dort_error_domain {
  static const DORT_ERROR_DOMAIN_NONE = 0;
  static const DORT_ERROR_DOMAIN_SHIM = 1;
  static const DORT_ERROR_DOMAIN_LOADER = 2;
  static const DORT_ERROR_DOMAIN_ORT_API = 3;
  static const DORT_ERROR_DOMAIN_ALLOCATION = 4;
  static const DORT_ERROR_DOMAIN_UNSUPPORTED = 5;
  static const DORT_ERROR_DOMAIN_ORT_STATUS = 6;
  static const DORT_ERROR_DOMAIN_PROVIDER = 7;
}

sealed class dort_error_code {
  static const DORT_ERROR_NONE = 0;
  static const DORT_ERROR_INVALID_ARGUMENT = 1;
  static const DORT_ERROR_ABI_MISMATCH = 2;
  static const DORT_ERROR_API_REQUEST_UNSUPPORTED = 3;
  static const DORT_ERROR_SOURCE_UNSUPPORTED = 4;
  static const DORT_ERROR_PATH_NOT_ABSOLUTE = 5;
  static const DORT_ERROR_PATH_OUTSIDE_ALLOWED_ROOT = 6;
  static const DORT_ERROR_RUNTIME_NOT_FOUND = 7;
  static const DORT_ERROR_SYMBOL_NOT_FOUND = 8;
  static const DORT_ERROR_ORT_API_UNAVAILABLE = 9;
  static const DORT_ERROR_ALLOCATION_FAILED = 10;
  static const DORT_ERROR_INVALID_UTF8 = 11;
  static const DORT_ERROR_LIMIT_EXCEEDED = 12;
  static const DORT_ERROR_PLATFORM = 13;
  static const DORT_ERROR_RUNTIME_IDENTITY_MISMATCH = 14;
  static const DORT_ERROR_MODEL_INVALID = 15;
  static const DORT_ERROR_TENSOR_INVALID = 16;
  static const DORT_ERROR_RUN_FAILED = 17;
  static const DORT_ERROR_BUFFER_TOO_SMALL = 18;
  static const DORT_ERROR_OVERFLOW = 19;
  static const DORT_ERROR_PROVIDER_UNSUPPORTED = 20;
  static const DORT_ERROR_NOT_TENSOR = 21;
  static const DORT_ERROR_VALUE_KIND_UNSUPPORTED = 22;
  static const DORT_ERROR_NOT_COMPOSITE = 23;
  static const DORT_ERROR_DATA_LEASE_UNSUPPORTED = 24;
  static const DORT_ERROR_MEMORY_DOMAIN_UNSUPPORTED = 25;
  static const DORT_ERROR_EXTERNAL_DATA_INVALID = 26;
  static const DORT_ERROR_CANCEL_TOKEN_UNKNOWN = 27;
  static const DORT_ERROR_CANCEL_REGISTRY_FULL = 28;
}

sealed class dort_graph_optimization_level {
  static const DORT_GRAPH_OPTIMIZATION_DISABLED = 0;
  static const DORT_GRAPH_OPTIMIZATION_BASIC = 1;
  static const DORT_GRAPH_OPTIMIZATION_EXTENDED = 2;
  static const DORT_GRAPH_OPTIMIZATION_ALL = 3;
}

sealed class dort_execution_mode {
  static const DORT_EXECUTION_SEQUENTIAL = 0;
  static const DORT_EXECUTION_PARALLEL = 1;
}

sealed class dort_tensor_element_type {
  static const DORT_TENSOR_FLOAT32 = 1;
  static const DORT_TENSOR_UINT8 = 2;
  static const DORT_TENSOR_INT8 = 3;
  static const DORT_TENSOR_UINT16 = 4;
  static const DORT_TENSOR_INT16 = 5;
  static const DORT_TENSOR_INT32 = 6;
  static const DORT_TENSOR_INT64 = 7;
  static const DORT_TENSOR_STRING = 8;
  static const DORT_TENSOR_BOOL = 9;
  static const DORT_TENSOR_FLOAT16 = 10;
  static const DORT_TENSOR_FLOAT64 = 11;
  static const DORT_TENSOR_UINT32 = 12;
  static const DORT_TENSOR_UINT64 = 13;
  static const DORT_TENSOR_BFLOAT16 = 16;
}

sealed class dort_value_kind {
  static const DORT_VALUE_KIND_TENSOR = 1;
  static const DORT_VALUE_KIND_SEQUENCE = 2;
  static const DORT_VALUE_KIND_MAP = 3;
  static const DORT_VALUE_KIND_OPTIONAL = 6;
}

final class dort_string extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int length;

  external ffi.Pointer<ffi.Void> private_owner;
}

typedef dort_string_t = dort_string;

final class dort_runtime_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int shim_abi_version;

  @ffi.Uint32()
  external int required_ort_api_version;

  @ffi.Uint32()
  external int source_kind;

  @ffi.Uint32()
  external int flags;

  @ffi.Uint32()
  external int log_severity;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> log_id_utf8;

  external ffi.Pointer<ffi.Char> library_path_utf8;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> preferred_library_names_utf8;

  @ffi.Size()
  external int preferred_library_name_count;

  external ffi.Pointer<ffi.Char> allowed_root_utf8;
}

typedef dort_runtime_config_t = dort_runtime_config;

final class dort_string_pair extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> key_utf8;

  external ffi.Pointer<ffi.Char> value_utf8;
}

typedef dort_string_pair_t = dort_string_pair;

final class dort_provider_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> provider_id_utf8;

  external ffi.Pointer<dort_string_pair_t> options;

  @ffi.Size()
  external int option_count;
}

typedef dort_provider_config_t = dort_provider_config;

final class dort_session_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int graph_optimization_level;

  @ffi.Uint32()
  external int execution_mode;

  @ffi.Int32()
  external int intra_op_thread_count;

  @ffi.Int32()
  external int inter_op_thread_count;

  @ffi.Uint32()
  external int enable_cpu_memory_arena;

  @ffi.Uint32()
  external int enable_memory_pattern;

  @ffi.Uint32()
  external int deterministic_compute;

  @ffi.Uint32()
  external int enable_profiling;

  @ffi.Uint32()
  external int log_severity;

  @ffi.Int32()
  external int log_verbosity;

  @ffi.Uint32()
  external int optimized_model_overwrite;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> log_id_utf8;

  external ffi.Pointer<ffi.Char> profile_path_prefix_utf8;

  external ffi.Pointer<ffi.Char> optimized_model_path_utf8;

  external ffi.Pointer<ffi.Char> artifact_root_utf8;

  @ffi.Size()
  external int max_model_bytes;

  external ffi.Pointer<dort_provider_config_t> providers;

  @ffi.Size()
  external int provider_count;

  external ffi.Pointer<dort_string_pair_t> config_entries;

  @ffi.Size()
  external int config_entry_count;
}

typedef dort_session_config_t = dort_session_config;

final class dort_named_value extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Char> name_utf8;

  external ffi.Pointer<dort_value_t> value;
}

typedef dort_named_value_t = dort_named_value;

final class dort_utf8_span extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int length;
}

typedef dort_utf8_span_t = dort_utf8_span;

final class dort_external_data extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int reserved0;

  external ffi.Pointer<ffi.Uint8> relative_name_utf8;

  @ffi.Size()
  external int relative_name_length;

  external ffi.Pointer<ffi.Void> data;

  @ffi.Size()
  external int data_length;
}

typedef dort_external_data_t = dort_external_data;

const int DORT_ABI_VERSION = 1;

const int DORT_ORT_API_COMPATIBILITY_FLOOR = 27;
