from __future__ import annotations

import hashlib
import os
from pathlib import Path
import signal
import sys
import tempfile
import textwrap
import time
import unittest
from unittest import mock


CI_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(CI_ROOT))

import android_gate_common as common  # noqa: E402


def _verification_metadata(
    *,
    configuration_extra: str = "",
    verify_metadata: str = "true",
    checksum_element: str = "sha256",
    checksum_value: str = "a" * 64,
) -> bytes:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<verification-metadata xmlns="https://schema.gradle.org/'
        'dependency-verification" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:schemaLocation="https://schema.gradle.org/dependency-verification '
        'https://schema.gradle.org/dependency-verification/'
        'dependency-verification-1.3.xsd">\n'
        "  <configuration>\n"
        f"    <verify-metadata>{verify_metadata}</verify-metadata>\n"
        "    <verify-signatures>false</verify-signatures>\n"
        f"{configuration_extra}"
        "  </configuration>\n"
        "  <components>\n"
        '    <component group="example" name="library" version="1.0">\n'
        '      <artifact name="library-1.0.jar">\n'
        f'        <{checksum_element} value="{checksum_value}" '
        'origin="Generated by Gradle"/>\n'
        "      </artifact>\n"
        "    </component>\n"
        "  </components>\n"
        "</verification-metadata>\n"
    ).encode("utf-8")


def _kill_pid(pid: int) -> None:
    try:
        os.kill(pid, signal.SIGKILL)
    except ProcessLookupError:
        pass


def _read_pids(path: Path) -> tuple[int, int]:
    parent, child = path.read_text(encoding="utf-8").split()
    return int(parent), int(child)


class RunBoundedTest(unittest.TestCase):
    def test_captures_stdout_and_stderr(self) -> None:
        result = common.run_bounded(
            [
                sys.executable,
                "-c",
                "import sys; print('out'); print('err', file=sys.stderr)",
            ],
            operation="capture test",
            timeout_seconds=5,
            maximum_output=1024,
        )

        self.assertEqual(result.stdout, "out\n")
        self.assertEqual(result.stderr, "err\n")

    @unittest.skipUnless(os.name == "posix", "requires POSIX process groups")
    def test_timeout_kills_descendant_that_ignores_termination(self) -> None:
        with tempfile.TemporaryDirectory(prefix="fonix-gate-timeout-") as temporary:
            root = Path(temporary)
            pid_file = root / "pids"
            marker = root / "descendant-finished"
            script = textwrap.dedent(
                """
                import os
                from pathlib import Path
                import subprocess
                import sys
                import time

                descendant = subprocess.Popen([
                    sys.executable,
                    "-c",
                    (
                        "import signal,sys,time; "
                        "from pathlib import Path; "
                        "signal.signal(signal.SIGTERM, signal.SIG_IGN); "
                        "time.sleep(1.5); "
                        "Path(sys.argv[1]).write_text('escaped', encoding='utf-8')"
                    ),
                    sys.argv[2],
                ])
                Path(sys.argv[1]).write_text(
                    f"{os.getpid()} {descendant.pid}", encoding="utf-8"
                )
                print("ready", flush=True)
                time.sleep(60)
                """
            )

            with self.assertRaisesRegex(
                common.AndroidGateCommonError, "timed out after 1 seconds"
            ):
                common.run_bounded(
                    [sys.executable, "-c", script, str(pid_file), str(marker)],
                    operation="timeout tree test",
                    timeout_seconds=1,
                    maximum_output=1024,
                )

            _, descendant_pid = _read_pids(pid_file)
            self.addCleanup(_kill_pid, descendant_pid)
            time.sleep(0.75)
            self.assertFalse(marker.exists())

    @unittest.skipUnless(os.name == "posix", "requires POSIX process groups")
    def test_output_overflow_kills_the_owned_process_group(self) -> None:
        with tempfile.TemporaryDirectory(prefix="fonix-gate-overflow-") as temporary:
            root = Path(temporary)
            pid_file = root / "pids"
            marker = root / "descendant-finished"
            script = textwrap.dedent(
                """
                import os
                from pathlib import Path
                import subprocess
                import sys
                import time

                descendant = subprocess.Popen([
                    sys.executable,
                    "-c",
                    (
                        "import signal,sys,time; "
                        "from pathlib import Path; "
                        "signal.signal(signal.SIGTERM, signal.SIG_IGN); "
                        "time.sleep(0.5); "
                        "Path(sys.argv[1]).write_text('escaped', encoding='utf-8')"
                    ),
                    sys.argv[2],
                ])
                Path(sys.argv[1]).write_text(
                    f"{os.getpid()} {descendant.pid}", encoding="utf-8"
                )
                sys.stdout.write("x" * 131072)
                sys.stdout.flush()
                time.sleep(60)
                """
            )

            with self.assertRaisesRegex(
                common.AndroidGateCommonError, "stdout exceeds 1024 bytes"
            ):
                common.run_bounded(
                    [sys.executable, "-c", script, str(pid_file), str(marker)],
                    operation="overflow tree test",
                    timeout_seconds=5,
                    maximum_output=1024,
                )

            _, descendant_pid = _read_pids(pid_file)
            self.addCleanup(_kill_pid, descendant_pid)
            time.sleep(0.75)
            self.assertFalse(marker.exists())

    @unittest.skipUnless(os.name == "posix", "requires POSIX process groups")
    def test_fails_when_an_escaped_descendant_keeps_pipes_open(self) -> None:
        with tempfile.TemporaryDirectory(prefix="fonix-gate-drain-") as temporary:
            pid_file = Path(temporary) / "pids"
            script = textwrap.dedent(
                """
                import os
                from pathlib import Path
                import subprocess
                import sys

                descendant = subprocess.Popen(
                    [sys.executable, "-c", "import time; time.sleep(30)"],
                    start_new_session=True,
                )
                Path(sys.argv[1]).write_text(
                    f"{os.getpid()} {descendant.pid}", encoding="utf-8"
                )
                """
            )
            started = time.monotonic()
            try:
                with (
                    mock.patch.object(
                        common, "PROCESS_TERMINATION_GRACE_SECONDS", 0.1
                    ),
                    mock.patch.object(common, "OUTPUT_DRAIN_GRACE_SECONDS", 0.1),
                ):
                    with self.assertRaisesRegex(
                        common.AndroidGateCommonError,
                        "stdout did not reach EOF after process termination",
                    ):
                        common.run_bounded(
                            [sys.executable, "-c", script, str(pid_file)],
                            operation="pipe drain test",
                            timeout_seconds=5,
                            maximum_output=1024,
                        )
            finally:
                if pid_file.exists():
                    _, descendant_pid = _read_pids(pid_file)
                    _kill_pid(descendant_pid)

            self.assertLess(time.monotonic() - started, 2.0)


class GradleDependencyVerificationTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(
            prefix="fonix-gradle-verification-"
        )
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.metadata = self.root / "verification-metadata.xml"

    def test_closed_metadata_identity_and_report(self) -> None:
        contents = _verification_metadata()
        self.metadata.write_bytes(contents)

        identity = common.gradle_verification_metadata_identity(
            self.metadata,
            "test Gradle verification metadata",
        )

        self.assertEqual(identity.size_bytes, len(contents))
        self.assertEqual(
            identity.sha256,
            hashlib.sha256(contents).hexdigest(),
        )
        self.assertEqual(
            common.gradle_verification_report(identity),
            {
                "mode": "strict",
                "sizeBytes": len(contents),
                "sha256": identity.sha256,
            },
        )

    def test_broad_trust_and_ignore_policies_are_rejected(self) -> None:
        unsafe_configuration = (
            "    <trusted-artifacts>\n"
            '      <trust group=".*" regex="true"/>\n'
            "    </trusted-artifacts>\n"
        )
        mutations = (
            _verification_metadata(configuration_extra=unsafe_configuration),
            _verification_metadata(
                configuration_extra=(
                    "    <ignored-components>\n"
                    '      <ignore group=".*" regex="true"/>\n'
                    "    </ignored-components>\n"
                )
            ),
            _verification_metadata(verify_metadata="false"),
            _verification_metadata(checksum_element="sha1"),
            _verification_metadata().replace(
                b"      </artifact>",
                b'        <sha256 value="' + b"b" * 64 + b'"/>\n'
                b"      </artifact>",
                1,
            ),
            _verification_metadata().replace(
                b"<verification-metadata ",
                b'<!DOCTYPE verification-metadata [<!ENTITY bypass "true">]>\n'
                b"<verification-metadata ",
                1,
            ),
        )
        for index, contents in enumerate(mutations):
            with self.subTest(index=index):
                self.metadata.write_bytes(contents)
                with self.assertRaises(common.AndroidGateCommonError):
                    common.gradle_verification_metadata_identity(
                        self.metadata,
                        "test Gradle verification metadata",
                    )

    def test_missing_symlink_and_identity_mutation_fail_closed(self) -> None:
        with self.assertRaisesRegex(
            common.AndroidGateCommonError,
            "missing test Gradle verification metadata",
        ):
            common.gradle_verification_metadata_identity(
                self.metadata,
                "test Gradle verification metadata",
            )

        target = self.root / "target.xml"
        target.write_bytes(_verification_metadata())
        if os.name != "nt":
            self.metadata.symlink_to(target)
            with self.assertRaisesRegex(
                common.AndroidGateCommonError,
                "not a regular file",
            ):
                common.gradle_verification_metadata_identity(
                    self.metadata,
                    "test Gradle verification metadata",
                )
            self.metadata.unlink()

        self.metadata.write_bytes(_verification_metadata())
        identity = common.gradle_verification_metadata_identity(
            self.metadata,
            "test Gradle verification metadata",
        )
        self.metadata.write_bytes(
            _verification_metadata(checksum_value="b" * 64)
        )
        with self.assertRaisesRegex(
            common.AndroidGateCommonError,
            "identity changed",
        ):
            common.require_gradle_verification_metadata_identity(
                self.metadata,
                identity,
                "test Gradle verification metadata",
            )

    def test_strict_environment_drops_ambient_bypasses(self) -> None:
        base = {
            "PATH": "/controlled/bin",
            "JAVA_HOME": "/controlled/jdk",
            "GRADLE_OPTS": "-Dorg.gradle.dependency.verification=off -Xmx8g",
            "java_opts": "-Dorg.gradle.dependency.verification=lenient",
            "JAVA_TOOL_OPTIONS": "-Dorg.gradle.dependency.verification=off",
            "_JAVA_OPTIONS": "-Dorg.gradle.dependency.verification=off",
            "JDK_JAVA_OPTIONS": "-Dorg.gradle.dependency.verification=off",
            "ORG_GRADLE_PROJECT_org.gradle.dependency.verification": "off",
            "org_gradle_project_org_gradle_dependency_verification": "lenient",
            "ORG.GRADLE.PROJECT.ORG.GRADLE.DEPENDENCY.VERIFICATION": "off",
            "ORG_GRADLE_PROJECT_unrelated": "preserved",
        }

        environment = common.strict_gradle_environment(base)

        self.assertEqual(environment["PATH"], "/controlled/bin")
        self.assertEqual(environment["JAVA_HOME"], "/controlled/jdk")
        self.assertEqual(
            environment["ORG_GRADLE_PROJECT_unrelated"],
            "preserved",
        )
        self.assertEqual(
            environment["GRADLE_OPTS"],
            "-Dorg.gradle.dependency.verification=strict",
        )
        self.assertNotIn("java_opts", environment)
        self.assertNotIn("JAVA_TOOL_OPTIONS", environment)
        self.assertNotIn("_JAVA_OPTIONS", environment)
        self.assertNotIn("JDK_JAVA_OPTIONS", environment)
        self.assertFalse(
            any(
                key.casefold().replace(".", "_")
                == "org_gradle_project_org_gradle_dependency_verification"
                for key in environment
            )
        )


if __name__ == "__main__":
    unittest.main()
