from __future__ import annotations

import base64
import copy
import hashlib
import importlib.util
import json
from pathlib import Path
import struct
import subprocess
import sys
import tempfile
import unittest
from unittest import mock
import zipfile


REPOSITORY = Path(__file__).resolve().parents[3]
SCRIPT = REPOSITORY / "tool/ci/validate_android_load_order_receipt.py"
SCHEMA = REPOSITORY / "templates/android/load_order_receipt.schema.json"
ELF_TESTS = REPOSITORY / "tool/tests/test_verify_native_libs.py"
_ELF_SPEC = importlib.util.spec_from_file_location(
    "fonix_load_order_elf_fixture", ELF_TESTS
)
assert _ELF_SPEC is not None and _ELF_SPEC.loader is not None
ELF_FIXTURE = importlib.util.module_from_spec(_ELF_SPEC)
_ELF_SPEC.loader.exec_module(ELF_FIXTURE)

_VALIDATOR_SPEC = importlib.util.spec_from_file_location(
    "fonix_load_order_validator", SCRIPT
)
assert _VALIDATOR_SPEC is not None and _VALIDATOR_SPEC.loader is not None
VALIDATOR = importlib.util.module_from_spec(_VALIDATOR_SPEC)
_VALIDATOR_SPEC.loader.exec_module(VALIDATOR)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _wav(samples: list[int], sample_rate: int = 16000) -> bytes:
    payload = struct.pack(f"<{len(samples)}h", *samples)
    fmt = struct.pack("<HHIIHH", 1, 1, sample_rate, sample_rate * 2, 2, 16)
    body = b"fmt " + struct.pack("<I", len(fmt)) + fmt
    body += b"data" + struct.pack("<I", len(payload)) + payload
    return b"RIFF" + struct.pack("<I", len(body) + 4) + b"WAVE" + body


class AndroidLoadOrderReceiptTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary_directory.cleanup)
        self.root = Path(self.temporary_directory.name)
        self.abi = "arm64-v8a"
        self.revision = "142807252687d81b40d6315f23470a1512a00de3"
        self.package_version = "1.13.4"

        self.launch_challenge = self._file("launch-challenge.bin", b"nonce-0001\n")
        self.fonix_model = self._file("fonix.onnx", b"synthetic fonix model\n")
        self.fonix_input = self._file("fonix-input.bin", b"synthetic fonix input\n")
        self.fonix_reference_output = self._file(
            "fonix-reference.f32", struct.pack("<ff", 1.25, -0.5)
        )
        self.fonix_cancellation_model = self._file(
            "fonix-cancellation.onnx", b"synthetic slow fonix model\n"
        )
        self.fonix_cancellation_input = self._file(
            "fonix-cancellation-input.bin", b"synthetic slow input\n"
        )
        self.sherpa_model = self._file("silero-vad.onnx", b"synthetic silero model\n")
        self.sherpa_audio = self._file("speech.wav", _wav([0] * 1024))
        self.pubspec_lock = self._file(
            "pubspec.lock",
            (
                "# Generated by pub\n"
                "# See https://dart.dev/tools/pub/glossary#lockfile\n"
                "packages:\n"
                "  sherpa_onnx:\n"
                '    dependency: "direct main"\n'
                "    description:\n"
                "      name: sherpa_onnx\n"
                "      sha256: "
                '"889c03cf7a8788795e3a6d35bf9f20b66d1862ea7a73a1b6aaf6e450715c870a"\n'
                '      url: "https://pub.dev"\n'
                "    source: hosted\n"
                f'    version: "{self.package_version}"\n'
                "  sherpa_onnx_android_arm64:\n"
                '    dependency: "direct overridden"\n'
                "    description:\n"
                "      name: sherpa_onnx_android_arm64\n"
                "      sha256: "
                '"0337650bc2357f39b751f1b9ced37770de3b60026effe66473b557346b4e3f97"\n'
                '      url: "https://pub.dev"\n'
                "    source: hosted\n"
                f'    version: "{self.package_version}"\n'
                "sdks:\n"
                '  dart: ">=3.12.0 <4.0.0"\n'
                '  flutter: ">=3.47.0-0.1.pre"\n'
            ).encode("utf-8"),
        )

        self.profile = {
            "id": "silero-vad-load-order-v1",
            "provider": "cpu",
            "sampleRateHz": 16000,
            "windowSamples": 512,
            "numThreads": 1,
            "thresholdMillionths": 500000,
            "minimumSpeechMilliseconds": 250,
            "minimumSilenceMilliseconds": 800,
            "maximumSpeechMilliseconds": 30000,
            "bufferMilliseconds": 60000,
        }
        self.sherpa_reference_value = {
            "schemaVersion": 1,
            "profile": self.profile,
            "audio": {"encoding": "wav-pcm-s16le-mono", "sampleCount": 1024},
            "invariant": {
                "minimumSegments": 1,
                "maximumSegments": 2,
                "minimumTotalSegmentSamples": 100,
                "maximumTotalSegmentSamples": 600,
                "maximumSegmentSamples": 600,
            },
        }
        self.sherpa_reference = self.root / "sherpa-reference.json"
        _write_json(self.sherpa_reference, self.sherpa_reference_value)

        self.ort_bytes = ELF_FIXTURE.synthetic_elf(
            self.abi,
            soname="libonnxruntime.so",
            needed=("libdl.so", "liblog.so", "libm.so", "libc.so"),
            defined_symbols=("OrtGetApiBase",),
        )
        self.shim_bytes = ELF_FIXTURE.synthetic_elf(
            self.abi,
            soname="libfonix_shim.so",
            needed=("libdl.so", "libc.so"),
        )
        self.sherpa_capi_bytes = ELF_FIXTURE.synthetic_elf(
            self.abi,
            soname="libsherpa-onnx-c-api.so",
            needed=("libonnxruntime.so", "libdl.so", "libc.so"),
        )
        self.sherpa_cxx_bytes = ELF_FIXTURE.synthetic_elf(
            self.abi,
            soname="libsherpa-onnx-cxx-api.so",
            needed=(
                "libsherpa-onnx-c-api.so",
                "libonnxruntime.so",
                "libdl.so",
                "libc.so",
            ),
        )
        self.final_apk = self.root / "app-release.apk"
        self._write_apk()

        reference_base64 = base64.b64encode(
            self.fonix_reference_output.read_bytes()
        ).decode("ascii")
        reference_hash = _sha256(self.fonix_reference_output)
        fonix_step = {
            "ordinal": 1,
            "engine": "fonix",
            "outputEncoding": "float32-le",
            "outputBytesBase64": reference_base64,
            "outputSha256": reference_hash,
        }
        sherpa_step = {
            "ordinal": 2,
            "engine": "sherpa",
            "sourceSamples": 1024,
            "submittedSamples": 1024,
            "segments": [{"startSample": 100, "sampleCount": 300}],
            "queueEmptyAfterDrain": True,
            "detectedAfterDrain": False,
        }
        self.receipt = {
            "schemaVersion": 2,
            "result": "passed",
            "matrix": {
                "abi": self.abi,
                "loadOrder": "dart-first",
                "buildType": "release-minified",
                "pageSizeBytes": 16384,
            },
            "build": {
                "applicationId": "dev.fonix.loadorder",
                "finalApkSha256": _sha256(self.final_apk),
                "harnessContractSha256": "0" * 64,
                "pubspecLockSha256": _sha256(self.pubspec_lock),
                "targetEvidenceSha256": "0" * 64,
                "logcatEvidenceSha256": "0" * 64,
            },
            "device": {
                "kind": "physical",
                "modelToken": "synthetic-arm64-device",
                "androidApi": 35,
                "fingerprintSha256": hashlib.sha256(b"fingerprint").hexdigest(),
            },
            "process": {
                "launchChallengeSha256": _sha256(self.launch_challenge),
                "uid": {
                    "packageManager": 10123,
                    "logcatFilter": 10123,
                    "receiptLine": 10123,
                },
                "pid": {
                    "beforeLaunch": None,
                    "observedAfterLaunch": 4321,
                    "logcatFilter": 4321,
                    "receiptLine": 4321,
                    "afterReceipt": 4321,
                    "afterForceStop": None,
                },
            },
            "runtime": {
                "runtimeOwner": "sherpa",
                "runtimeSource": "process",
                "ortVersion": "1.27.0",
                "requiredOrtApi": 27,
                "negotiatedOrtApi": 27,
                "ortSha256": hashlib.sha256(self.ort_bytes).hexdigest(),
                "shimAbi": 1,
                "shimBuildId": "android-owner-sherpa-source-process",
            },
            "sherpa": {
                "packageVersion": self.package_version,
                "nativeVersion": self.package_version,
                "sourceRevision": self.revision,
                "nativeRevision": self.revision[:12],
                "profile": self.profile,
            },
            "fixtures": {
                "fonixModelSha256": _sha256(self.fonix_model),
                "fonixInputSha256": _sha256(self.fonix_input),
                "fonixReferenceOutputSha256": reference_hash,
                "fonixCancellationModelSha256": _sha256(self.fonix_cancellation_model),
                "fonixCancellationInputSha256": _sha256(self.fonix_cancellation_input),
                "sherpaModelSha256": _sha256(self.sherpa_model),
                "sherpaAudioSha256": _sha256(self.sherpa_audio),
                "sherpaReferenceSha256": _sha256(self.sherpa_reference),
            },
            "initialization": {
                "events": ["fonix-session-ready", "sherpa-vad-ready"],
                "firstOwnerAliveWhenSecondReady": True,
            },
            "workload": {
                "requestedCycles": 2,
                "completedCycles": 2,
                "steps": [
                    fonix_step,
                    sherpa_step,
                    {**fonix_step, "ordinal": 3},
                    {**sherpa_step, "ordinal": 4},
                ],
            },
            "lifecycle": {
                "fonixCancellation": {
                    "mode": "active-native-termination",
                    "requestCount": 1,
                    "nativeRequestAcceptedCount": 1,
                    "settlementCount": 1,
                    "cancelledResultCount": 1,
                    "publishedOutputCount": 0,
                    "outstandingRunsAfterSettlement": 0,
                    "settledBeforeRecovery": True,
                },
                "sherpaCancellation": {
                    "mode": "between-bounded-frames",
                    "requestCount": 1,
                    "framesAcceptedBeforeRequest": 1,
                    "framesAcceptedAfterRequest": 0,
                    "flushCallsAfterRequest": 0,
                    "segmentsPublishedAfterRequest": 0,
                    "detectorRetiredBeforeRecovery": True,
                },
                "staleCompletion": {
                    "inducedCount": 1,
                    "observedCount": 1,
                    "suppressedCount": 1,
                    "publishedOutputCount": 0,
                    "retiredGeneration": 7,
                    "authoritativeGeneration": 8,
                },
                "recovery": {
                    "fonixOutputEncoding": "float32-le",
                    "fonixOutputBytesBase64": reference_base64,
                    "fonixOutputSha256": reference_hash,
                    "sherpa": {
                        "sourceSamples": 1024,
                        "submittedSamples": 1024,
                        "segments": [{"startSample": 100, "sampleCount": 300}],
                        "queueEmptyAfterDrain": True,
                        "detectedAfterDrain": False,
                    },
                },
                "disposal": {
                    "ordersTested": ["fonix-then-sherpa", "sherpa-then-fonix"],
                    "fonixSessionsCreated": 2,
                    "fonixSessionsClosed": 2,
                    "sherpaDetectorsCreated": 2,
                    "sherpaDetectorsFreed": 2,
                    "fonixDoubleClose": "passed",
                    "sherpaDoubleFree": "passed",
                    "pendingFonixRuns": 0,
                    "queuedSherpaSegments": 0,
                    "temporaryRootsCreated": 2,
                    "temporaryRootsRemoved": 2,
                    "temporaryRootsRemaining": 0,
                },
            },
        }
        self.receipt_path = self.root / "receipt.json"
        self.harness_contract = self.root / "harness.json"
        self.target_evidence = self.root / "target.json"
        self.logcat_evidence = self.root / "logcat.json"
        self._rewrite_evidence()

    def _file(self, name: str, contents: bytes) -> Path:
        path = self.root / name
        path.write_bytes(contents)
        return path

    def _write_apk(
        self,
        *,
        include_cxx: bool = True,
        include_jni: bool = False,
        extra_libraries: tuple[tuple[str, bytes], ...] = (),
    ) -> None:
        with zipfile.ZipFile(self.final_apk, "w") as archive:
            archive.writestr("AndroidManifest.xml", b"synthetic manifest")
            archive.writestr(f"lib/{self.abi}/libonnxruntime.so", self.ort_bytes)
            archive.writestr(f"lib/{self.abi}/libfonix_shim.so", self.shim_bytes)
            archive.writestr(
                f"lib/{self.abi}/libsherpa-onnx-c-api.so", self.sherpa_capi_bytes
            )
            if include_cxx:
                archive.writestr(
                    f"lib/{self.abi}/libsherpa-onnx-cxx-api.so",
                    self.sherpa_cxx_bytes,
                )
            if include_jni:
                archive.writestr(
                    f"lib/{self.abi}/libsherpa-onnx-jni.so",
                    ELF_FIXTURE.synthetic_elf(
                        self.abi,
                        soname="libsherpa-onnx-jni.so",
                        needed=("libonnxruntime.so", "libc.so"),
                    ),
                )
            for name, contents in extra_libraries:
                archive.writestr(f"lib/{self.abi}/{name}", contents)

    def _rewrite_evidence(self) -> None:
        self.receipt["build"].update(
            {
                "finalApkSha256": _sha256(self.final_apk),
                "pubspecLockSha256": _sha256(self.pubspec_lock),
            }
        )
        harness = {
            "schemaVersion": 1,
            "applicationId": self.receipt["build"]["applicationId"],
            "finalApkSha256": self.receipt["build"]["finalApkSha256"],
            "pubspecLockSha256": self.receipt["build"]["pubspecLockSha256"],
            "profileId": self.receipt["sherpa"]["profile"]["id"],
            "requestedCycles": self.receipt["workload"]["requestedCycles"],
            "runtime": self.receipt["runtime"],
            "fixtures": self.receipt["fixtures"],
            "cancellationModes": {
                "fonix": "active-native-termination",
                "sherpa": "between-bounded-frames",
            },
        }
        _write_json(self.harness_contract, harness)
        self.receipt["build"]["harnessContractSha256"] = _sha256(
            self.harness_contract
        )
        target = {
            "schemaVersion": 1,
            "result": "passed",
            "applicationId": self.receipt["build"]["applicationId"],
            "finalApkSha256": self.receipt["build"]["finalApkSha256"],
            "harnessContractSha256": self.receipt["build"][
                "harnessContractSha256"
            ],
            "pubspecLockSha256": self.receipt["build"]["pubspecLockSha256"],
            "launchChallengeSha256": self.receipt["process"]["launchChallengeSha256"],
            "matrix": self.receipt["matrix"],
            "device": self.receipt["device"],
            "fixtures": self.receipt["fixtures"],
            "process": {
                "uid": self.receipt["process"]["uid"],
                "pid": self.receipt["process"]["pid"],
            },
            "runtime": self.receipt["runtime"],
            "sherpa": self.receipt["sherpa"],
            "initialization": self.receipt["initialization"],
            "workload": self.receipt["workload"],
            "lifecycle": self.receipt["lifecycle"],
        }
        _write_json(self.target_evidence, target)
        logcat = {
            "schemaVersion": 1,
            "result": "passed",
            "applicationId": self.receipt["build"]["applicationId"],
            "deviceFingerprintSha256": self.receipt["device"]["fingerprintSha256"],
            "finalApkSha256": self.receipt["build"]["finalApkSha256"],
            "harnessContractSha256": self.receipt["build"][
                "harnessContractSha256"
            ],
            "fixtures": self.receipt["fixtures"],
            "targetEvidenceSha256": _sha256(self.target_evidence),
            "launchChallengeSha256": self.receipt["process"]["launchChallengeSha256"],
            "uid": self.receipt["process"]["uid"]["receiptLine"],
            "pid": self.receipt["process"]["pid"]["receiptLine"],
        }
        _write_json(self.logcat_evidence, logcat)
        self.receipt["build"].update(
            {
                "targetEvidenceSha256": _sha256(self.target_evidence),
                "logcatEvidenceSha256": _sha256(self.logcat_evidence),
            }
        )
        _write_json(self.receipt_path, self.receipt)

    def _arguments(self, output: Path) -> list[str]:
        return [
            "--receipt",
            str(self.receipt_path),
            "--target-evidence",
            str(self.target_evidence),
            "--logcat-evidence",
            str(self.logcat_evidence),
            "--launch-challenge",
            str(self.launch_challenge),
            "--final-apk",
            str(self.final_apk),
            "--harness-contract",
            str(self.harness_contract),
            "--pubspec-lock",
            str(self.pubspec_lock),
            "--fonix-model",
            str(self.fonix_model),
            "--fonix-input",
            str(self.fonix_input),
            "--fonix-reference-output",
            str(self.fonix_reference_output),
            "--fonix-cancellation-model",
            str(self.fonix_cancellation_model),
            "--fonix-cancellation-input",
            str(self.fonix_cancellation_input),
            "--sherpa-model",
            str(self.sherpa_model),
            "--sherpa-audio",
            str(self.sherpa_audio),
            "--sherpa-reference",
            str(self.sherpa_reference),
            "--sherpa-revision",
            self.revision,
            "--output",
            str(output),
        ]

    def _run(
        self, name: str | Path = "validated.json"
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), *self._arguments(self.root / name)],
            cwd=REPOSITORY,
            check=False,
            capture_output=True,
            text=True,
        )

    def _assert_rejected(self, expected: str) -> None:
        result = self._run()
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn(expected, result.stderr)
        self.assertFalse((self.root / "validated.json").exists())

    def test_accepts_complete_evidence_and_output_is_path_free_deterministic(self) -> None:
        first = self._run("first.json")
        self.assertEqual(first.returncode, 0, first.stderr)
        second = self._run("second.json")
        self.assertEqual(second.returncode, 0, second.stderr)
        first_bytes = (self.root / "first.json").read_bytes()
        self.assertEqual(first_bytes, (self.root / "second.json").read_bytes())
        record = json.loads(first_bytes)
        self.assertEqual(record["schemaVersion"], 1)
        self.assertEqual(record["result"], "passed")
        self.assertEqual(
            set(record),
            {
                "schemaVersion",
                "result",
                "claimStatus",
                "targetEvidenceProvenance",
                "validatorSha256",
                "receiptSchemaSha256",
                "nativeVerifierSha256",
                "loadOrderReceiptSha256",
                "matrix",
                "build",
                "device",
                "process",
                "runtime",
                "sherpa",
                "fixtures",
                "initialization",
                "workload",
                "lifecycle",
                "evidenceBindings",
                "nativeLibraries",
                "claimBoundary",
            },
        )
        self.assertNotIn(str(self.root), first_bytes.decode("utf-8"))
        self.assertEqual(record["claimStatus"], "offline-consistency-only")
        self.assertEqual(record["targetEvidenceProvenance"], "unverified")
        self.assertIn("between bounded VAD frames", record["claimBoundary"])
        self.assertIn("does not authenticate", record["claimBoundary"])
        self.assertIn("trusted capture provenance remains required", record["claimBoundary"])
        self.assertEqual(record["validatorSha256"], _sha256(SCRIPT))
        self.assertEqual(record["receiptSchemaSha256"], _sha256(SCHEMA))
        self.assertEqual(record["nativeVerifierSha256"], _sha256(VALIDATOR.VERIFIER_PATH))
        self.assertEqual(
            record["evidenceBindings"]["receiptSchema"],
            {"sizeBytes": SCHEMA.stat().st_size, "sha256": _sha256(SCHEMA)},
        )
        self.assertEqual(
            record["evidenceBindings"]["nativeVerifier"],
            {
                "sizeBytes": VALIDATOR.VERIFIER_PATH.stat().st_size,
                "sha256": _sha256(VALIDATOR.VERIFIER_PATH),
            },
        )
        self.assertEqual(
            record["nativeLibraries"]["onnxRuntime"]["sha256"],
            self.receipt["runtime"]["ortSha256"],
        )

    def test_accepts_4k_page_device_receipt(self) -> None:
        self.receipt["matrix"]["pageSizeBytes"] = 4096
        self._rewrite_evidence()
        result = self._run()
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_accepts_sherpa_first_receipt(self) -> None:
        self.receipt["matrix"]["loadOrder"] = "sherpa-first"
        self.receipt["initialization"]["events"] = [
            "sherpa-vad-ready",
            "fonix-session-ready",
        ]
        self._rewrite_evidence()
        result = self._run()
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_schema_is_v2_and_closed(self) -> None:
        schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        self.assertEqual(schema["properties"]["schemaVersion"]["const"], 2)
        self.assertFalse(schema["additionalProperties"])
        self.assertFalse(schema["$defs"]["lifecycle"]["additionalProperties"])
        VALIDATOR._validate_schema_document(schema)

        duplicated = copy.deepcopy(schema)
        duplicated["$defs"]["sherpaProfile"]["required"].append("id")
        with self.assertRaisesRegex(
            VALIDATOR.LoadOrderReceiptError, "unique string property names"
        ):
            VALIDATOR._validate_schema_document(duplicated)

    def test_receipt_is_checked_against_the_repository_schema(self) -> None:
        schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        schema["$defs"]["matrix"]["properties"]["abi"] = {"const": "x86_64"}
        alternate_schema = self.root / "alternate.schema.json"
        _write_json(alternate_schema, schema)
        arguments = VALIDATOR._parser().parse_args(
            self._arguments(self.root / "validated.json")
        )
        with mock.patch.object(VALIDATOR, "RECEIPT_SCHEMA_PATH", alternate_schema):
            with self.assertRaisesRegex(
                VALIDATOR.LoadOrderReceiptError, "schema constant"
            ):
                VALIDATOR.validate(arguments)

    def test_rejects_duplicate_json_keys(self) -> None:
        self.receipt_path.write_text(
            '{"schemaVersion":2,"schemaVersion":2}\n', encoding="utf-8"
        )
        self._assert_rejected("duplicate JSON key")

    def test_rejects_non_finite_json(self) -> None:
        self.receipt_path.write_text('{"schemaVersion":NaN}\n', encoding="utf-8")
        self._assert_rejected("non-finite JSON value")

    def test_rejects_independently_tampered_cli_file(self) -> None:
        self.fonix_model.write_bytes(b"tampered model\n")
        self._assert_rejected("Fonix model hash does not match")

    def test_rejects_apk_change_not_endorsed_by_target_evidence(self) -> None:
        with zipfile.ZipFile(self.final_apk, "a") as archive:
            archive.writestr("assets/tamper.bin", b"changed build")
        self.receipt["build"]["finalApkSha256"] = _sha256(self.final_apk)
        harness = json.loads(self.harness_contract.read_text(encoding="utf-8"))
        harness["finalApkSha256"] = self.receipt["build"]["finalApkSha256"]
        _write_json(self.harness_contract, harness)
        self.receipt["build"]["harnessContractSha256"] = _sha256(
            self.harness_contract
        )
        _write_json(self.receipt_path, self.receipt)
        self._assert_rejected("target evidence does not exactly reproduce")

    def test_rejects_runtime_too_old_for_required_c_api(self) -> None:
        self.receipt["runtime"]["ortVersion"] = "1.23.2"
        self._rewrite_evidence()
        self._assert_rejected("cannot expose the required ORT C API 27")

    def test_rejects_caller_supplied_sherpa_revision_outside_closed_provenance(
        self,
    ) -> None:
        self.revision = "0123456789abcdef0123456789abcdef01234567"
        self.receipt["sherpa"]["sourceRevision"] = self.revision
        self.receipt["sherpa"]["nativeRevision"] = self.revision[:12]
        self._rewrite_evidence()
        self._assert_rejected("outside the closed provenance set")

    def test_rejects_float_and_boolean_substitutes_for_schema_integers(self) -> None:
        mutations = (
            lambda receipt: receipt.update({"schemaVersion": 2.0}),
            lambda receipt: receipt["matrix"].update({"pageSizeBytes": 16384.0}),
            lambda receipt: receipt["runtime"].update({"requiredOrtApi": 27.0}),
            lambda receipt: receipt["runtime"].update({"negotiatedOrtApi": 27.0}),
            lambda receipt: receipt["runtime"].update({"shimAbi": True}),
            lambda receipt: receipt["workload"].update({"completedCycles": 2.0}),
            lambda receipt: receipt["lifecycle"]["sherpaCancellation"].update(
                {"requestCount": True}
            ),
            lambda receipt: receipt["lifecycle"]["disposal"].update(
                {"fonixSessionsClosed": 2.0}
            ),
        )
        for index, mutate in enumerate(mutations):
            with self.subTest(index=index):
                original = copy.deepcopy(self.receipt)
                mutate(self.receipt)
                self._rewrite_evidence()
                result = self._run(f"numeric-rejected-{index}.json")
                self.assertNotEqual(result.returncode, 0, result.stdout)
                self.assertIn("schema", result.stderr)
                self.assertFalse(
                    (self.root / f"numeric-rejected-{index}.json").exists()
                )
                self.receipt = original
                self._rewrite_evidence()

    def test_rejects_non_integer_sherpa_reference_counts(self) -> None:
        reference = copy.deepcopy(self.sherpa_reference_value)
        reference["audio"]["sampleCount"] = 1024.0
        _write_json(self.sherpa_reference, reference)
        self.receipt["fixtures"]["sherpaReferenceSha256"] = _sha256(
            self.sherpa_reference
        )
        self._rewrite_evidence()
        self._assert_rejected("Sherpa reference.audio.sampleCount must be an integer")

    def test_rejects_malformed_pubspec_lock_without_packages_root(self) -> None:
        self.pubspec_lock.write_text(
            (
                "  sherpa_onnx:\n"
                f'    version: "{self.package_version}"\n'
                "  sherpa_onnx_android_arm64:\n"
                f'    version: "{self.package_version}"\n'
            ),
            encoding="utf-8",
        )
        self._rewrite_evidence()
        self._assert_rejected("precedes its packages root")

    def test_rejects_untrusted_sherpa_lockfile_provenance(self) -> None:
        original = self.pubspec_lock.read_text(encoding="utf-8")
        mutations = (
            (
                'dependency: "direct overridden"',
                'dependency: "transitive"',
                "wrong dependency mode",
            ),
            ("source: hosted", "source: path", "invalid path description"),
            (
                "name: sherpa_onnx_android_arm64",
                "name: sherpa_onnx_android_x86_64",
                "wrong hosted name",
            ),
            (
                'url: "https://pub.dev"',
                'url: "https://example.invalid"',
                "wrong hosted URL",
            ),
            (
                'sha256: "0337650bc2357f39b751f1b9ced37770de3b60026effe66473b557346b4e3f97"',
                'sha256: "0337650BC2357F39B751F1B9CED37770DE3B60026EFFE66473B557346B4E3F97"',
                "lowercase SHA-256",
            ),
            (
                'sha256: "0337650bc2357f39b751f1b9ced37770de3b60026effe66473b557346b4e3f97"',
                f'sha256: "{"c" * 64}"',
                "wrong hosted SHA-256",
            ),
        )
        for index, (old, new, expected) in enumerate(mutations):
            with self.subTest(index=index):
                self.pubspec_lock.write_text(
                    original.replace(old, new, 1), encoding="utf-8"
                )
                self._rewrite_evidence()
                result = self._run(f"lock-rejected-{index}.json")
                self.assertNotEqual(result.returncode, 0, result.stdout)
                self.assertIn(expected, result.stderr)
                self.assertFalse((self.root / f"lock-rejected-{index}.json").exists())
        self.pubspec_lock.write_text(original, encoding="utf-8")
        self._rewrite_evidence()

    def test_rejects_malformed_content_outside_selected_pubspec_packages(self) -> None:
        original = self.pubspec_lock.read_text(encoding="utf-8")
        mutations = (
            original + "broken: [\n",
            original.replace(
                "sdks:\n",
                "  unrelated:\n"
                "    dependency: transitive\n"
                "    description: flutter\n"
                "    malformed\n"
                "sdks:\n",
            ),
        )
        for index, contents in enumerate(mutations):
            with self.subTest(index=index):
                self.pubspec_lock.write_text(contents, encoding="utf-8")
                self._rewrite_evidence()
                result = self._run(f"malformed-lock-{index}.json")
                self.assertNotEqual(result.returncode, 0, result.stdout)
                self.assertIn("pubspec.lock", result.stderr)
                self.assertFalse((self.root / f"malformed-lock-{index}.json").exists())

    def test_rejects_apk_changed_during_native_inspection(self) -> None:
        arguments = VALIDATOR._parser().parse_args(
            self._arguments(self.root / "validated.json")
        )
        inspect = VALIDATOR.VERIFIER.inspect

        def inspect_then_mutate(path: Path) -> dict[str, object]:
            report = inspect(path)
            path.chmod(0o600)
            with path.open("ab") as sink:
                sink.write(b"changed-after-inspection")
            return report

        with mock.patch.object(
            VALIDATOR.VERIFIER, "inspect", side_effect=inspect_then_mutate
        ):
            with self.assertRaisesRegex(
                VALIDATOR.LoadOrderReceiptError,
                "final APK snapshot changed while it was being inspected",
            ):
                VALIDATOR.validate(arguments)

    def test_inspects_an_exact_private_snapshot_despite_original_path_aba(self) -> None:
        arguments = VALIDATOR._parser().parse_args(
            self._arguments(self.root / "validated.json")
        )
        expected_bytes = self.final_apk.read_bytes()
        inspect = VALIDATOR.VERIFIER.inspect
        inspected_paths: list[Path] = []

        def inspect_during_original_aba(path: Path) -> dict[str, object]:
            inspected_paths.append(path)
            self.assertNotEqual(path, self.final_apk)
            self.assertEqual(path.read_bytes(), expected_bytes)
            original = self.root / "original.apk"
            self.final_apk.rename(original)
            self.final_apk.write_bytes(b"substituted bytes")
            self.final_apk.unlink()
            original.rename(self.final_apk)
            return inspect(path)

        with mock.patch.object(
            VALIDATOR.VERIFIER, "inspect", side_effect=inspect_during_original_aba
        ):
            record = VALIDATOR.validate(arguments)
        self.assertEqual(record["evidenceBindings"]["finalApk"]["sha256"], _sha256(self.final_apk))
        self.assertEqual(len(inspected_paths), 1)
        self.assertFalse(inspected_paths[0].exists())

    def test_rejects_output_or_temporary_output_overlapping_an_input(self) -> None:
        inside_input = self._run(self.fonix_model / "validated.json")
        self.assertNotEqual(inside_input.returncode, 0)
        self.assertIn("must not overlap an input", inside_input.stderr)

        colliding_input = self.root / "collision.json.tmp"
        self.launch_challenge.rename(colliding_input)
        self.launch_challenge = colliding_input
        temporary_collision = self._run("collision.json")
        self.assertNotEqual(temporary_collision.returncode, 0)
        self.assertIn("must not overlap an input", temporary_collision.stderr)

    def test_atomic_publication_never_overwrites_a_racing_destination(self) -> None:
        output = self.root / "racing-output.json"
        real_link = VALIDATOR.os.link

        def create_destination_before_link(
            source: Path, destination: Path, *, follow_symlinks: bool
        ) -> None:
            Path(destination).write_bytes(b"racing owner\n")
            real_link(source, destination, follow_symlinks=follow_symlinks)

        with mock.patch.object(VALIDATOR.os, "link", side_effect=create_destination_before_link):
            with self.assertRaises(FileExistsError):
                VALIDATOR._write_new(output, {"result": "passed"})
        self.assertEqual(output.read_bytes(), b"racing owner\n")
        self.assertFalse((self.root / "racing-output.json.tmp").exists())

        second_output = self.root / "racing-temporary-output.json"
        temporary = self.root / "racing-temporary-output.json.tmp"
        real_open = VALIDATOR.os.open

        def create_temporary_before_open(
            path: Path, flags: int, mode: int = 0o777
        ) -> int:
            Path(path).write_bytes(b"temporary owner\n")
            return real_open(path, flags, mode)

        with mock.patch.object(VALIDATOR.os, "open", side_effect=create_temporary_before_open):
            with self.assertRaises(FileExistsError):
                VALIDATOR._write_new(second_output, {"result": "passed"})
        self.assertEqual(temporary.read_bytes(), b"temporary owner\n")
        self.assertFalse(second_output.exists())

        mutated_output = self.root / "mutated-publication.json"

        def mutate_owned_inode_after_link(
            source: Path, destination: Path, *, follow_symlinks: bool
        ) -> None:
            real_link(source, destination, follow_symlinks=follow_symlinks)
            published = Path(destination)
            published.write_bytes(
                published.read_bytes().replace(b'"passed"', b'"failed"')
            )

        with mock.patch.object(
            VALIDATOR.os, "link", side_effect=mutate_owned_inode_after_link
        ):
            with self.assertRaisesRegex(
                VALIDATOR.LoadOrderReceiptError,
                "published output changed during publication",
            ):
                VALIDATOR._write_new(mutated_output, {"result": "passed"})
        self.assertFalse(mutated_output.exists())
        self.assertFalse((self.root / "mutated-publication.json.tmp").exists())

        failed_output = self.root / "failed-publication.json"

        def fail_after_link(
            source: Path, destination: Path, *, follow_symlinks: bool
        ) -> None:
            real_link(source, destination, follow_symlinks=follow_symlinks)
            raise OSError("synthetic post-link failure")

        with mock.patch.object(VALIDATOR.os, "link", side_effect=fail_after_link):
            with self.assertRaisesRegex(OSError, "synthetic post-link failure"):
                VALIDATOR._write_new(failed_output, {"result": "passed"})
        self.assertFalse(failed_output.exists())
        self.assertFalse((self.root / "failed-publication.json.tmp").exists())

    def test_rejects_unselected_sherpa_jni_in_final_apk(self) -> None:
        self._write_apk(include_jni=True)
        self._rewrite_evidence()
        self._assert_rejected("not JNI")

    def test_rejects_missing_sherpa_cxx_api_in_final_apk(self) -> None:
        self._write_apk(include_cxx=False)
        self._rewrite_evidence()
        self._assert_rejected("exactly one libsherpa-onnx-cxx-api.so")

    def test_rejects_closed_soname_alias_and_unaligned_extra_library(self) -> None:
        cases = (
            (
                "libort-alias.so",
                ELF_FIXTURE.synthetic_elf(
                    self.abi,
                    soname="libonnxruntime.so",
                    needed=("libc.so",),
                ),
                "aliases closed SONAME",
            ),
            (
                "libsecond-runtime.so",
                ELF_FIXTURE.synthetic_elf(
                    self.abi,
                    soname="libsecond-runtime.so",
                    needed=("libc.so",),
                    defined_symbols=("OrtGetApiBase",),
                ),
                "hidden or invalid ONNX Runtime candidate",
            ),
            (
                "libunaligned.so",
                ELF_FIXTURE.synthetic_elf(
                    self.abi,
                    alignment=4096,
                    soname="libunaligned.so",
                    needed=("libc.so",),
                ),
                "not 16 KiB page compatible",
            ),
            (
                "libunresolved.so",
                ELF_FIXTURE.synthetic_elf(
                    self.abi,
                    soname="libunresolved.so",
                    needed=("libdoes-not-exist.so", "libc.so"),
                ),
                "unresolved DT_NEEDED",
            ),
        )
        for index, (name, contents, expected) in enumerate(cases):
            with self.subTest(name=name):
                self._write_apk(extra_libraries=((name, contents),))
                self._rewrite_evidence()
                result = self._run(f"native-rejected-{index}.json")
                self.assertNotEqual(result.returncode, 0, result.stdout)
                self.assertIn(expected, result.stderr)
                self.assertFalse((self.root / f"native-rejected-{index}.json").exists())

    def test_rejects_process_provenance_mismatch(self) -> None:
        logcat = json.loads(self.logcat_evidence.read_text(encoding="utf-8"))
        logcat["pid"] += 1
        _write_json(self.logcat_evidence, logcat)
        self.receipt["build"]["logcatEvidenceSha256"] = _sha256(self.logcat_evidence)
        _write_json(self.receipt_path, self.receipt)
        self._assert_rejected("does not bind the target process")

    def test_rejects_non_reference_fonix_bytes_and_non_alternating_steps(self) -> None:
        mutations = (
            lambda receipt: receipt["workload"]["steps"][0].update(
                {
                    "outputBytesBase64": base64.b64encode(struct.pack("<ff", 0.0, 0.0)).decode("ascii"),
                    "outputSha256": hashlib.sha256(struct.pack("<ff", 0.0, 0.0)).hexdigest(),
                }
            ),
            lambda receipt: receipt["workload"]["steps"][1].update({"engine": "fonix"}),
        )
        for index, mutate in enumerate(mutations):
            with self.subTest(index=index):
                original = copy.deepcopy(self.receipt)
                mutate(self.receipt)
                self._rewrite_evidence()
                result = self._run(f"rejected-{index}.json")
                self.assertNotEqual(result.returncode, 0, result.stdout)
                self.assertFalse((self.root / f"rejected-{index}.json").exists())
                self.receipt = original
                self._rewrite_evidence()

    def test_rejects_vad_segment_outside_reference(self) -> None:
        self.receipt["workload"]["steps"][1]["segments"] = [
            {"startSample": 900, "sampleCount": 300}
        ]
        self._rewrite_evidence()
        self._assert_rejected("overlapping or out of range")

    def test_rejects_missing_lifecycle_contract_fields(self) -> None:
        mutations = (
            lambda receipt: receipt["lifecycle"]["fonixCancellation"].pop(
                "nativeRequestAcceptedCount"
            ),
            lambda receipt: receipt["lifecycle"]["recovery"].pop("sherpa"),
            lambda receipt: receipt["lifecycle"]["disposal"].pop(
                "sherpaDoubleFree"
            ),
        )
        for index, mutate in enumerate(mutations):
            with self.subTest(index=index):
                original = copy.deepcopy(self.receipt)
                mutate(self.receipt)
                self._rewrite_evidence()
                result = self._run(f"lifecycle-missing-{index}.json")
                self.assertNotEqual(result.returncode, 0, result.stdout)
                self.assertIn("schema-required", result.stderr)
                self.assertFalse(
                    (self.root / f"lifecycle-missing-{index}.json").exists()
                )
                self.receipt = original
                self._rewrite_evidence()

    def test_rejects_dishonest_cancellation_and_incomplete_cleanup(self) -> None:
        mutations = (
            lambda receipt: receipt["lifecycle"]["fonixCancellation"].update(
                {"nativeRequestAcceptedCount": 0}
            ),
            lambda receipt: receipt["lifecycle"]["sherpaCancellation"].update(
                {"mode": "mid-native-call"}
            ),
            lambda receipt: receipt["lifecycle"]["sherpaCancellation"].update(
                {"framesAcceptedAfterRequest": 1}
            ),
            lambda receipt: receipt["lifecycle"]["sherpaCancellation"].update(
                {"framesAcceptedBeforeRequest": 2}
            ),
            lambda receipt: receipt["lifecycle"]["staleCompletion"].update(
                {
                    "retiredGeneration": 1_000_000,
                    "authoritativeGeneration": 1_000_001,
                }
            ),
            lambda receipt: receipt["lifecycle"]["disposal"].update(
                {"temporaryRootsRemaining": 1}
            ),
            lambda receipt: receipt["lifecycle"]["disposal"].update(
                {"fonixSessionsClosed": 1}
            ),
            lambda receipt: receipt["lifecycle"]["disposal"].update(
                {"fonixDoubleClose": "failed"}
            ),
        )
        for index, mutate in enumerate(mutations):
            with self.subTest(index=index):
                original = copy.deepcopy(self.receipt)
                mutate(self.receipt)
                self._rewrite_evidence()
                result = self._run(f"lifecycle-rejected-{index}.json")
                self.assertNotEqual(result.returncode, 0, result.stdout)
                self.assertFalse((self.root / f"lifecycle-rejected-{index}.json").exists())
                self.receipt = original
                self._rewrite_evidence()


if __name__ == "__main__":
    unittest.main()
